// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countActivityByUser = `-- name: CountActivityByUser :one
SELECT COUNT(*) FROM activity_log WHERE user_id = ?
`

func (q *Queries) CountActivityByUser(ctx context.Context, userID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivityByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivity = `-- name: CreateActivity :one

INSERT INTO activity_log (user_id, action, entity_type, entity_id, metadata)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, "action", entity_type, entity_id, metadata, created_at
`

type CreateActivityParams struct {
	UserID     sql.NullInt64  `json:"userId"`
	Action     string         `json:"action"`
	EntityType string         `json:"entityType"`
	EntityID   int64          `json:"entityId"`
	Metadata   sql.NullString `json:"metadata"`
}

// ============================================
// Activity Log Queries
// ============================================
func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (ActivityLog, error) {
	row := q.db.QueryRowContext(ctx, createActivity,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldActivity = `-- name: DeleteOldActivity :exec
DELETE FROM activity_log 
WHERE created_at < datetime('now', '-' || ? || ' days')
`

// Clean up activity logs older than N days
func (q *Queries) DeleteOldActivity(ctx context.Context, dollar_1 sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteOldActivity, dollar_1)
	return err
}

const listActivityByEntity = `-- name: ListActivityByEntity :many
SELECT 
    a.id, a.user_id, a."action", a.entity_type, a.entity_id, a.metadata, a.created_at,
    u.username,
    u.full_name
FROM activity_log a
LEFT JOIN users u ON a.user_id = u.id
WHERE a.entity_type = ? AND a.entity_id = ?
ORDER BY a.created_at DESC
LIMIT ?
`

type ListActivityByEntityParams struct {
	EntityType string `json:"entityType"`
	EntityID   int64  `json:"entityId"`
	Limit      int64  `json:"limit"`
}

type ListActivityByEntityRow struct {
	ID         int64          `json:"id"`
	UserID     sql.NullInt64  `json:"userId"`
	Action     string         `json:"action"`
	EntityType string         `json:"entityType"`
	EntityID   int64          `json:"entityId"`
	Metadata   sql.NullString `json:"metadata"`
	CreatedAt  time.Time      `json:"createdAt"`
	Username   sql.NullString `json:"username"`
	FullName   sql.NullString `json:"fullName"`
}

func (q *Queries) ListActivityByEntity(ctx context.Context, arg ListActivityByEntityParams) ([]ListActivityByEntityRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivityByEntity, arg.EntityType, arg.EntityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityByEntityRow{}
	for rows.Next() {
		var i ListActivityByEntityRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
			&i.Username,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityByUser = `-- name: ListActivityByUser :many
SELECT 
    a.id, a.user_id, a."action", a.entity_type, a.entity_id, a.metadata, a.created_at,
    u.username,
    u.full_name
FROM activity_log a
LEFT JOIN users u ON a.user_id = u.id
WHERE a.user_id = ?
ORDER BY a.created_at DESC
LIMIT ?
`

type ListActivityByUserParams struct {
	UserID sql.NullInt64 `json:"userId"`
	Limit  int64         `json:"limit"`
}

type ListActivityByUserRow struct {
	ID         int64          `json:"id"`
	UserID     sql.NullInt64  `json:"userId"`
	Action     string         `json:"action"`
	EntityType string         `json:"entityType"`
	EntityID   int64          `json:"entityId"`
	Metadata   sql.NullString `json:"metadata"`
	CreatedAt  time.Time      `json:"createdAt"`
	Username   sql.NullString `json:"username"`
	FullName   sql.NullString `json:"fullName"`
}

func (q *Queries) ListActivityByUser(ctx context.Context, arg ListActivityByUserParams) ([]ListActivityByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivityByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityByUserRow{}
	for rows.Next() {
		var i ListActivityByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
			&i.Username,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentActivity = `-- name: ListRecentActivity :many
SELECT 
    a.id, a.user_id, a."action", a.entity_type, a.entity_id, a.metadata, a.created_at,
    u.username,
    u.full_name,
    u.avatar_url
FROM activity_log a
LEFT JOIN users u ON a.user_id = u.id
ORDER BY a.created_at DESC
LIMIT ?
`

type ListRecentActivityRow struct {
	ID         int64          `json:"id"`
	UserID     sql.NullInt64  `json:"userId"`
	Action     string         `json:"action"`
	EntityType string         `json:"entityType"`
	EntityID   int64          `json:"entityId"`
	Metadata   sql.NullString `json:"metadata"`
	CreatedAt  time.Time      `json:"createdAt"`
	Username   sql.NullString `json:"username"`
	FullName   sql.NullString `json:"fullName"`
	AvatarUrl  sql.NullString `json:"avatarUrl"`
}

func (q *Queries) ListRecentActivity(ctx context.Context, limit int64) ([]ListRecentActivityRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentActivity, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentActivityRow{}
	for rows.Next() {
		var i ListRecentActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
