// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: doc_comments.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countCommentsByDoc = `-- name: CountCommentsByDoc :one
SELECT COUNT(*) FROM doc_comments WHERE doc_id = ?
`

func (q *Queries) CountCommentsByDoc(ctx context.Context, docID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCommentsByDoc, docID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocComment = `-- name: CreateDocComment :one
INSERT INTO doc_comments (doc_id, author_id, content)
VALUES (?, ?, ?)
RETURNING id, doc_id, author_id, content, created_at, updated_at
`

type CreateDocCommentParams struct {
	DocID    int64  `json:"docId"`
	AuthorID int64  `json:"authorId"`
	Content  string `json:"content"`
}

func (q *Queries) CreateDocComment(ctx context.Context, arg CreateDocCommentParams) (DocComment, error) {
	row := q.db.QueryRowContext(ctx, createDocComment, arg.DocID, arg.AuthorID, arg.Content)
	var i DocComment
	err := row.Scan(
		&i.ID,
		&i.DocID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocComment = `-- name: DeleteDocComment :exec
DELETE FROM doc_comments WHERE id = ?
`

func (q *Queries) DeleteDocComment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDocComment, id)
	return err
}

const deleteDocCommentByAuthor = `-- name: DeleteDocCommentByAuthor :execrows
DELETE FROM doc_comments WHERE id = ? AND author_id = ?
`

type DeleteDocCommentByAuthorParams struct {
	ID       int64 `json:"id"`
	AuthorID int64 `json:"authorId"`
}

// Only allow author to delete their own comment
func (q *Queries) DeleteDocCommentByAuthor(ctx context.Context, arg DeleteDocCommentByAuthorParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDocCommentByAuthor, arg.ID, arg.AuthorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDocCommentByID = `-- name: GetDocCommentByID :one

SELECT c.id, c.doc_id, c.author_id, c.content, c.created_at, c.updated_at, u.username as author_username, u.full_name as author_full_name, u.avatar_url as author_avatar
FROM doc_comments c
JOIN users u ON c.author_id = u.id
WHERE c.id = ? LIMIT 1
`

type GetDocCommentByIDRow struct {
	ID             int64          `json:"id"`
	DocID          int64          `json:"docId"`
	AuthorID       int64          `json:"authorId"`
	Content        string         `json:"content"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	AuthorUsername string         `json:"authorUsername"`
	AuthorFullName string         `json:"authorFullName"`
	AuthorAvatar   sql.NullString `json:"authorAvatar"`
}

// ============================================
// Doc Comment Queries
// ============================================
func (q *Queries) GetDocCommentByID(ctx context.Context, id int64) (GetDocCommentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDocCommentByID, id)
	var i GetDocCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.DocID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorUsername,
		&i.AuthorFullName,
		&i.AuthorAvatar,
	)
	return i, err
}

const listCommentsByDoc = `-- name: ListCommentsByDoc :many
SELECT c.id, c.doc_id, c.author_id, c.content, c.created_at, c.updated_at, u.username as author_username, u.full_name as author_full_name, u.avatar_url as author_avatar
FROM doc_comments c
JOIN users u ON c.author_id = u.id
WHERE c.doc_id = ?
ORDER BY c.created_at ASC
`

type ListCommentsByDocRow struct {
	ID             int64          `json:"id"`
	DocID          int64          `json:"docId"`
	AuthorID       int64          `json:"authorId"`
	Content        string         `json:"content"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	AuthorUsername string         `json:"authorUsername"`
	AuthorFullName string         `json:"authorFullName"`
	AuthorAvatar   sql.NullString `json:"authorAvatar"`
}

func (q *Queries) ListCommentsByDoc(ctx context.Context, docID int64) ([]ListCommentsByDocRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByDoc, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsByDocRow{}
	for rows.Next() {
		var i ListCommentsByDocRow
		if err := rows.Scan(
			&i.ID,
			&i.DocID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.AuthorFullName,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
