// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: docs.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countDocs = `-- name: CountDocs :one
SELECT COUNT(*) FROM docs WHERE is_published = 1
`

func (q *Queries) CountDocs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDocs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocsByProject = `-- name: CountDocsByProject :one
SELECT COUNT(*) FROM docs WHERE project_id = ? AND is_published = 1
`

func (q *Queries) CountDocsByProject(ctx context.Context, projectID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDocsByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDoc = `-- name: CreateDoc :one
INSERT INTO docs (project_id, slug, title, content, parent_id, sort_order, author_id, is_published)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, slug, title, content, parent_id, sort_order, author_id, last_editor_id, is_published, created_at, updated_at
`

type CreateDocParams struct {
	ProjectID   sql.NullInt64  `json:"projectId"`
	Slug        string         `json:"slug"`
	Title       string         `json:"title"`
	Content     sql.NullString `json:"content"`
	ParentID    sql.NullInt64  `json:"parentId"`
	SortOrder   int64          `json:"sortOrder"`
	AuthorID    int64          `json:"authorId"`
	IsPublished bool           `json:"isPublished"`
}

func (q *Queries) CreateDoc(ctx context.Context, arg CreateDocParams) (Doc, error) {
	row := q.db.QueryRowContext(ctx, createDoc,
		arg.ProjectID,
		arg.Slug,
		arg.Title,
		arg.Content,
		arg.ParentID,
		arg.SortOrder,
		arg.AuthorID,
		arg.IsPublished,
	)
	var i Doc
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.ParentID,
		&i.SortOrder,
		&i.AuthorID,
		&i.LastEditorID,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDoc = `-- name: DeleteDoc :exec
DELETE FROM docs WHERE id = ?
`

func (q *Queries) DeleteDoc(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDoc, id)
	return err
}

const getDocByID = `-- name: GetDocByID :one

SELECT 
    d.id, d.project_id, d.slug, d.title, d.content, d.parent_id, d.sort_order, d.author_id, d.last_editor_id, d.is_published, d.created_at, d.updated_at,
    p.key as project_key,
    p.name as project_name,
    a.username as author_username,
    a.full_name as author_full_name,
    e.username as editor_username
FROM docs d
LEFT JOIN projects p ON d.project_id = p.id
JOIN users a ON d.author_id = a.id
LEFT JOIN users e ON d.last_editor_id = e.id
WHERE d.id = ? LIMIT 1
`

type GetDocByIDRow struct {
	ID             int64          `json:"id"`
	ProjectID      sql.NullInt64  `json:"projectId"`
	Slug           string         `json:"slug"`
	Title          string         `json:"title"`
	Content        sql.NullString `json:"content"`
	ParentID       sql.NullInt64  `json:"parentId"`
	SortOrder      int64          `json:"sortOrder"`
	AuthorID       int64          `json:"authorId"`
	LastEditorID   sql.NullInt64  `json:"lastEditorId"`
	IsPublished    bool           `json:"isPublished"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	ProjectKey     string         `json:"projectKey"`
	ProjectName    string         `json:"projectName"`
	AuthorUsername string         `json:"authorUsername"`
	AuthorFullName string         `json:"authorFullName"`
	EditorUsername sql.NullString `json:"editorUsername"`
}

// ============================================
// Doc Queries (The Library)
// ============================================
func (q *Queries) GetDocByID(ctx context.Context, id int64) (GetDocByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDocByID, id)
	var i GetDocByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.ParentID,
		&i.SortOrder,
		&i.AuthorID,
		&i.LastEditorID,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectKey,
		&i.ProjectName,
		&i.AuthorUsername,
		&i.AuthorFullName,
		&i.EditorUsername,
	)
	return i, err
}

const getDocBySlug = `-- name: GetDocBySlug :one
SELECT 
    d.id, d.project_id, d.slug, d.title, d.content, d.parent_id, d.sort_order, d.author_id, d.last_editor_id, d.is_published, d.created_at, d.updated_at,
    p.key as project_key,
    p.name as project_name,
    a.username as author_username,
    a.full_name as author_full_name,
    e.username as editor_username
FROM docs d
LEFT JOIN projects p ON d.project_id = p.id
JOIN users a ON d.author_id = a.id
LEFT JOIN users e ON d.last_editor_id = e.id
WHERE d.slug = ? LIMIT 1
`

type GetDocBySlugRow struct {
	ID             int64          `json:"id"`
	ProjectID      sql.NullInt64  `json:"projectId"`
	Slug           string         `json:"slug"`
	Title          string         `json:"title"`
	Content        sql.NullString `json:"content"`
	ParentID       sql.NullInt64  `json:"parentId"`
	SortOrder      int64          `json:"sortOrder"`
	AuthorID       int64          `json:"authorId"`
	LastEditorID   sql.NullInt64  `json:"lastEditorId"`
	IsPublished    bool           `json:"isPublished"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	ProjectKey     string         `json:"projectKey"`
	ProjectName    string         `json:"projectName"`
	AuthorUsername string         `json:"authorUsername"`
	AuthorFullName string         `json:"authorFullName"`
	EditorUsername sql.NullString `json:"editorUsername"`
}

func (q *Queries) GetDocBySlug(ctx context.Context, slug string) (GetDocBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getDocBySlug, slug)
	var i GetDocBySlugRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.ParentID,
		&i.SortOrder,
		&i.AuthorID,
		&i.LastEditorID,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectKey,
		&i.ProjectName,
		&i.AuthorUsername,
		&i.AuthorFullName,
		&i.EditorUsername,
	)
	return i, err
}

const getDocTree = `-- name: GetDocTree :many
WITH RECURSIVE doc_tree AS (
    SELECT id, parent_id, title, slug, sort_order, 0 as depth
    FROM docs
    WHERE parent_id IS NULL AND is_published = 1
    
    UNION ALL
    
    SELECT d.id, d.parent_id, d.title, d.slug, d.sort_order, dt.depth + 1
    FROM docs d
    JOIN doc_tree dt ON d.parent_id = dt.id
    WHERE d.is_published = 1
)
SELECT id, parent_id, title, slug, sort_order, depth FROM doc_tree ORDER BY depth, sort_order, title
`

type GetDocTreeRow struct {
	ID        int64         `json:"id"`
	ParentID  sql.NullInt64 `json:"parentId"`
	Title     string        `json:"title"`
	Slug      string        `json:"slug"`
	SortOrder int64         `json:"sortOrder"`
	Depth     int64         `json:"depth"`
}

// Recursive CTE to get full doc tree (SQLite 3.8.3+)
func (q *Queries) GetDocTree(ctx context.Context) ([]GetDocTreeRow, error) {
	rows, err := q.db.QueryContext(ctx, getDocTree)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDocTreeRow{}
	for rows.Next() {
		var i GetDocTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Title,
			&i.Slug,
			&i.SortOrder,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllDocs = `-- name: ListAllDocs :many
SELECT 
    d.id, d.project_id, d.slug, d.title, d.content, d.parent_id, d.sort_order, d.author_id, d.last_editor_id, d.is_published, d.created_at, d.updated_at,
    p.key as project_key,
    a.username as author_username
FROM docs d
LEFT JOIN projects p ON d.project_id = p.id
JOIN users a ON d.author_id = a.id
ORDER BY d.project_id, d.parent_id, d.sort_order, d.title
`

type ListAllDocsRow struct {
	ID             int64          `json:"id"`
	ProjectID      sql.NullInt64  `json:"projectId"`
	Slug           string         `json:"slug"`
	Title          string         `json:"title"`
	Content        sql.NullString `json:"content"`
	ParentID       sql.NullInt64  `json:"parentId"`
	SortOrder      int64          `json:"sortOrder"`
	AuthorID       int64          `json:"authorId"`
	LastEditorID   sql.NullInt64  `json:"lastEditorId"`
	IsPublished    bool           `json:"isPublished"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	ProjectKey     string         `json:"projectKey"`
	AuthorUsername string         `json:"authorUsername"`
}

// Include unpublished (for admin)
func (q *Queries) ListAllDocs(ctx context.Context) ([]ListAllDocsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllDocs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllDocsRow{}
	for rows.Next() {
		var i ListAllDocsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Slug,
			&i.Title,
			&i.Content,
			&i.ParentID,
			&i.SortOrder,
			&i.AuthorID,
			&i.LastEditorID,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectKey,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocs = `-- name: ListDocs :many
SELECT 
    d.id, d.project_id, d.slug, d.title, d.content, d.parent_id, d.sort_order, d.author_id, d.last_editor_id, d.is_published, d.created_at, d.updated_at,
    p.key as project_key,
    a.username as author_username
FROM docs d
LEFT JOIN projects p ON d.project_id = p.id
JOIN users a ON d.author_id = a.id
WHERE d.parent_id IS NULL AND d.is_published = 1
ORDER BY d.sort_order, d.title
`

type ListDocsRow struct {
	ID             int64          `json:"id"`
	ProjectID      sql.NullInt64  `json:"projectId"`
	Slug           string         `json:"slug"`
	Title          string         `json:"title"`
	Content        sql.NullString `json:"content"`
	ParentID       sql.NullInt64  `json:"parentId"`
	SortOrder      int64          `json:"sortOrder"`
	AuthorID       int64          `json:"authorId"`
	LastEditorID   sql.NullInt64  `json:"lastEditorId"`
	IsPublished    bool           `json:"isPublished"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	ProjectKey     string         `json:"projectKey"`
	AuthorUsername string         `json:"authorUsername"`
}

// List all root-level docs (no parent)
func (q *Queries) ListDocs(ctx context.Context) ([]ListDocsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocsRow{}
	for rows.Next() {
		var i ListDocsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Slug,
			&i.Title,
			&i.Content,
			&i.ParentID,
			&i.SortOrder,
			&i.AuthorID,
			&i.LastEditorID,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectKey,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocsByParent = `-- name: ListDocsByParent :many
SELECT 
    d.id, d.project_id, d.slug, d.title, d.content, d.parent_id, d.sort_order, d.author_id, d.last_editor_id, d.is_published, d.created_at, d.updated_at,
    a.username as author_username
FROM docs d
JOIN users a ON d.author_id = a.id
WHERE d.parent_id = ? AND d.is_published = 1
ORDER BY d.sort_order, d.title
`

type ListDocsByParentRow struct {
	ID             int64          `json:"id"`
	ProjectID      sql.NullInt64  `json:"projectId"`
	Slug           string         `json:"slug"`
	Title          string         `json:"title"`
	Content        sql.NullString `json:"content"`
	ParentID       sql.NullInt64  `json:"parentId"`
	SortOrder      int64          `json:"sortOrder"`
	AuthorID       int64          `json:"authorId"`
	LastEditorID   sql.NullInt64  `json:"lastEditorId"`
	IsPublished    bool           `json:"isPublished"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	AuthorUsername string         `json:"authorUsername"`
}

// Get children of a doc (for tree navigation)
func (q *Queries) ListDocsByParent(ctx context.Context, parentID sql.NullInt64) ([]ListDocsByParentRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocsByParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocsByParentRow{}
	for rows.Next() {
		var i ListDocsByParentRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Slug,
			&i.Title,
			&i.Content,
			&i.ParentID,
			&i.SortOrder,
			&i.AuthorID,
			&i.LastEditorID,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocsByProject = `-- name: ListDocsByProject :many
SELECT 
    d.id, d.project_id, d.slug, d.title, d.content, d.parent_id, d.sort_order, d.author_id, d.last_editor_id, d.is_published, d.created_at, d.updated_at,
    a.username as author_username
FROM docs d
JOIN users a ON d.author_id = a.id
WHERE d.project_id = ? AND d.is_published = 1
ORDER BY d.sort_order, d.title
`

type ListDocsByProjectRow struct {
	ID             int64          `json:"id"`
	ProjectID      sql.NullInt64  `json:"projectId"`
	Slug           string         `json:"slug"`
	Title          string         `json:"title"`
	Content        sql.NullString `json:"content"`
	ParentID       sql.NullInt64  `json:"parentId"`
	SortOrder      int64          `json:"sortOrder"`
	AuthorID       int64          `json:"authorId"`
	LastEditorID   sql.NullInt64  `json:"lastEditorId"`
	IsPublished    bool           `json:"isPublished"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	AuthorUsername string         `json:"authorUsername"`
}

func (q *Queries) ListDocsByProject(ctx context.Context, projectID sql.NullInt64) ([]ListDocsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocsByProjectRow{}
	for rows.Next() {
		var i ListDocsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Slug,
			&i.Title,
			&i.Content,
			&i.ParentID,
			&i.SortOrder,
			&i.AuthorID,
			&i.LastEditorID,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDocs = `-- name: SearchDocs :many
SELECT 
    d.id, d.project_id, d.slug, d.title, d.content, d.parent_id, d.sort_order, d.author_id, d.last_editor_id, d.is_published, d.created_at, d.updated_at,
    p.key as project_key,
    a.username as author_username
FROM docs d
LEFT JOIN projects p ON d.project_id = p.id
JOIN users a ON d.author_id = a.id
WHERE (d.title LIKE '%' || ? || '%' OR d.content LIKE '%' || ? || '%')
  AND d.is_published = 1
ORDER BY d.updated_at DESC
LIMIT ?
`

type SearchDocsParams struct {
	Column1 sql.NullString `json:"column1"`
	Column2 sql.NullString `json:"column2"`
	Limit   int64          `json:"limit"`
}

type SearchDocsRow struct {
	ID             int64          `json:"id"`
	ProjectID      sql.NullInt64  `json:"projectId"`
	Slug           string         `json:"slug"`
	Title          string         `json:"title"`
	Content        sql.NullString `json:"content"`
	ParentID       sql.NullInt64  `json:"parentId"`
	SortOrder      int64          `json:"sortOrder"`
	AuthorID       int64          `json:"authorId"`
	LastEditorID   sql.NullInt64  `json:"lastEditorId"`
	IsPublished    bool           `json:"isPublished"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	ProjectKey     string         `json:"projectKey"`
	AuthorUsername string         `json:"authorUsername"`
}

func (q *Queries) SearchDocs(ctx context.Context, arg SearchDocsParams) ([]SearchDocsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchDocs, arg.Column1, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDocsRow{}
	for rows.Next() {
		var i SearchDocsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Slug,
			&i.Title,
			&i.Content,
			&i.ParentID,
			&i.SortOrder,
			&i.AuthorID,
			&i.LastEditorID,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectKey,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDoc = `-- name: UpdateDoc :one
UPDATE docs SET
    title = COALESCE(?, title),
    content = COALESCE(?, content),
    parent_id = ?,
    sort_order = COALESCE(?, sort_order),
    last_editor_id = ?,
    is_published = COALESCE(?, is_published),
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, project_id, slug, title, content, parent_id, sort_order, author_id, last_editor_id, is_published, created_at, updated_at
`

type UpdateDocParams struct {
	Title        string         `json:"title"`
	Content      sql.NullString `json:"content"`
	ParentID     sql.NullInt64  `json:"parentId"`
	SortOrder    int64          `json:"sortOrder"`
	LastEditorID sql.NullInt64  `json:"lastEditorId"`
	IsPublished  bool           `json:"isPublished"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateDoc(ctx context.Context, arg UpdateDocParams) (Doc, error) {
	row := q.db.QueryRowContext(ctx, updateDoc,
		arg.Title,
		arg.Content,
		arg.ParentID,
		arg.SortOrder,
		arg.LastEditorID,
		arg.IsPublished,
		arg.ID,
	)
	var i Doc
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.ParentID,
		&i.SortOrder,
		&i.AuthorID,
		&i.LastEditorID,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDocSlug = `-- name: UpdateDocSlug :exec
UPDATE docs SET slug = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateDocSlugParams struct {
	Slug string `json:"slug"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateDocSlug(ctx context.Context, arg UpdateDocSlugParams) error {
	_, err := q.db.ExecContext(ctx, updateDocSlug, arg.Slug, arg.ID)
	return err
}
