// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issues.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countIssuesByProject = `-- name: CountIssuesByProject :one
SELECT COUNT(*) FROM issues WHERE project_id = ?
`

func (q *Queries) CountIssuesByProject(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIssuesByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIssuesByStatus = `-- name: CountIssuesByStatus :one
SELECT COUNT(*) FROM issues WHERE project_id = ? AND status = ?
`

type CountIssuesByStatusParams struct {
	ProjectID int64  `json:"projectId"`
	Status    string `json:"status"`
}

func (q *Queries) CountIssuesByStatus(ctx context.Context, arg CountIssuesByStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIssuesByStatus, arg.ProjectID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIssue = `-- name: CreateIssue :one
INSERT INTO issues (
    project_id, issue_number, title, description, status, priority, 
    issue_type, rank, reporter_id, assignee_id, parent_id, labels, 
    story_points, due_date
)
VALUES (?, 0, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, issue_number, title, description, status, priority, issue_type, rank, reporter_id, assignee_id, parent_id, labels, story_points, due_date, resolved_at, created_at, updated_at
`

type CreateIssueParams struct {
	ProjectID   int64          `json:"projectId"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	Priority    string         `json:"priority"`
	IssueType   string         `json:"issueType"`
	Rank        string         `json:"rank"`
	ReporterID  int64          `json:"reporterId"`
	AssigneeID  sql.NullInt64  `json:"assigneeId"`
	ParentID    sql.NullInt64  `json:"parentId"`
	Labels      sql.NullString `json:"labels"`
	StoryPoints sql.NullInt64  `json:"storyPoints"`
	DueDate     sql.NullTime   `json:"dueDate"`
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, createIssue,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.IssueType,
		arg.Rank,
		arg.ReporterID,
		arg.AssigneeID,
		arg.ParentID,
		arg.Labels,
		arg.StoryPoints,
		arg.DueDate,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IssueNumber,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.IssueType,
		&i.Rank,
		&i.ReporterID,
		&i.AssigneeID,
		&i.ParentID,
		&i.Labels,
		&i.StoryPoints,
		&i.DueDate,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIssue = `-- name: DeleteIssue :exec
DELETE FROM issues WHERE id = ?
`

func (q *Queries) DeleteIssue(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteIssue, id)
	return err
}

const getIssueByID = `-- name: GetIssueByID :one

SELECT 
    i.id, i.project_id, i.issue_number, i.title, i.description, i.status, i.priority, i.issue_type, i.rank, i.reporter_id, i.assignee_id, i.parent_id, i.labels, i.story_points, i.due_date, i.resolved_at, i.created_at, i.updated_at,
    p.key as project_key,
    p.name as project_name,
    r.username as reporter_username,
    r.full_name as reporter_full_name,
    a.username as assignee_username,
    a.full_name as assignee_full_name
FROM issues i
JOIN projects p ON i.project_id = p.id
JOIN users r ON i.reporter_id = r.id
LEFT JOIN users a ON i.assignee_id = a.id
WHERE i.id = ? LIMIT 1
`

type GetIssueByIDRow struct {
	ID               int64          `json:"id"`
	ProjectID        int64          `json:"projectId"`
	IssueNumber      int64          `json:"issueNumber"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	Status           string         `json:"status"`
	Priority         string         `json:"priority"`
	IssueType        string         `json:"issueType"`
	Rank             string         `json:"rank"`
	ReporterID       int64          `json:"reporterId"`
	AssigneeID       sql.NullInt64  `json:"assigneeId"`
	ParentID         sql.NullInt64  `json:"parentId"`
	Labels           sql.NullString `json:"labels"`
	StoryPoints      sql.NullInt64  `json:"storyPoints"`
	DueDate          sql.NullTime   `json:"dueDate"`
	ResolvedAt       sql.NullTime   `json:"resolvedAt"`
	CreatedAt        time.Time      `json:"createdAt"`
	UpdatedAt        time.Time      `json:"updatedAt"`
	ProjectKey       string         `json:"projectKey"`
	ProjectName      string         `json:"projectName"`
	ReporterUsername string         `json:"reporterUsername"`
	ReporterFullName string         `json:"reporterFullName"`
	AssigneeUsername sql.NullString `json:"assigneeUsername"`
	AssigneeFullName sql.NullString `json:"assigneeFullName"`
}

// ============================================
// Issue Queries (The Tablet)
// ============================================
func (q *Queries) GetIssueByID(ctx context.Context, id int64) (GetIssueByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getIssueByID, id)
	var i GetIssueByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IssueNumber,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.IssueType,
		&i.Rank,
		&i.ReporterID,
		&i.AssigneeID,
		&i.ParentID,
		&i.Labels,
		&i.StoryPoints,
		&i.DueDate,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectKey,
		&i.ProjectName,
		&i.ReporterUsername,
		&i.ReporterFullName,
		&i.AssigneeUsername,
		&i.AssigneeFullName,
	)
	return i, err
}

const getIssueByProjectAndNumber = `-- name: GetIssueByProjectAndNumber :one
SELECT 
    i.id, i.project_id, i.issue_number, i.title, i.description, i.status, i.priority, i.issue_type, i.rank, i.reporter_id, i.assignee_id, i.parent_id, i.labels, i.story_points, i.due_date, i.resolved_at, i.created_at, i.updated_at,
    p.key as project_key,
    p.name as project_name,
    r.username as reporter_username,
    r.full_name as reporter_full_name,
    a.username as assignee_username,
    a.full_name as assignee_full_name
FROM issues i
JOIN projects p ON i.project_id = p.id
JOIN users r ON i.reporter_id = r.id
LEFT JOIN users a ON i.assignee_id = a.id
WHERE p.key = ? COLLATE NOCASE AND i.issue_number = ?
LIMIT 1
`

type GetIssueByProjectAndNumberParams struct {
	Key         string `json:"key"`
	IssueNumber int64  `json:"issueNumber"`
}

type GetIssueByProjectAndNumberRow struct {
	ID               int64          `json:"id"`
	ProjectID        int64          `json:"projectId"`
	IssueNumber      int64          `json:"issueNumber"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	Status           string         `json:"status"`
	Priority         string         `json:"priority"`
	IssueType        string         `json:"issueType"`
	Rank             string         `json:"rank"`
	ReporterID       int64          `json:"reporterId"`
	AssigneeID       sql.NullInt64  `json:"assigneeId"`
	ParentID         sql.NullInt64  `json:"parentId"`
	Labels           sql.NullString `json:"labels"`
	StoryPoints      sql.NullInt64  `json:"storyPoints"`
	DueDate          sql.NullTime   `json:"dueDate"`
	ResolvedAt       sql.NullTime   `json:"resolvedAt"`
	CreatedAt        time.Time      `json:"createdAt"`
	UpdatedAt        time.Time      `json:"updatedAt"`
	ProjectKey       string         `json:"projectKey"`
	ProjectName      string         `json:"projectName"`
	ReporterUsername string         `json:"reporterUsername"`
	ReporterFullName string         `json:"reporterFullName"`
	AssigneeUsername sql.NullString `json:"assigneeUsername"`
	AssigneeFullName sql.NullString `json:"assigneeFullName"`
}

func (q *Queries) GetIssueByProjectAndNumber(ctx context.Context, arg GetIssueByProjectAndNumberParams) (GetIssueByProjectAndNumberRow, error) {
	row := q.db.QueryRowContext(ctx, getIssueByProjectAndNumber, arg.Key, arg.IssueNumber)
	var i GetIssueByProjectAndNumberRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IssueNumber,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.IssueType,
		&i.Rank,
		&i.ReporterID,
		&i.AssigneeID,
		&i.ParentID,
		&i.Labels,
		&i.StoryPoints,
		&i.DueDate,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectKey,
		&i.ProjectName,
		&i.ReporterUsername,
		&i.ReporterFullName,
		&i.AssigneeUsername,
		&i.AssigneeFullName,
	)
	return i, err
}

const getMaxRankInStatus = `-- name: GetMaxRankInStatus :one
SELECT COALESCE(MAX(rank), '') FROM issues WHERE project_id = ? AND status = ?
`

type GetMaxRankInStatusParams struct {
	ProjectID int64  `json:"projectId"`
	Status    string `json:"status"`
}

// Get the highest rank in a status column for inserting at the end
func (q *Queries) GetMaxRankInStatus(ctx context.Context, arg GetMaxRankInStatusParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxRankInStatus, arg.ProjectID, arg.Status)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getNextIssueNumber = `-- name: GetNextIssueNumber :one
SELECT COALESCE(MAX(issue_number), 0) + 1 FROM issues WHERE project_id = ?
`

func (q *Queries) GetNextIssueNumber(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextIssueNumber, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listIssuesByAssignee = `-- name: ListIssuesByAssignee :many
SELECT 
    i.id, i.project_id, i.issue_number, i.title, i.description, i.status, i.priority, i.issue_type, i.rank, i.reporter_id, i.assignee_id, i.parent_id, i.labels, i.story_points, i.due_date, i.resolved_at, i.created_at, i.updated_at,
    p.key as project_key,
    p.name as project_name,
    r.username as reporter_username
FROM issues i
JOIN projects p ON i.project_id = p.id
JOIN users r ON i.reporter_id = r.id
WHERE i.assignee_id = ?
ORDER BY i.status, i.priority DESC, i.created_at DESC
`

type ListIssuesByAssigneeRow struct {
	ID               int64          `json:"id"`
	ProjectID        int64          `json:"projectId"`
	IssueNumber      int64          `json:"issueNumber"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	Status           string         `json:"status"`
	Priority         string         `json:"priority"`
	IssueType        string         `json:"issueType"`
	Rank             string         `json:"rank"`
	ReporterID       int64          `json:"reporterId"`
	AssigneeID       sql.NullInt64  `json:"assigneeId"`
	ParentID         sql.NullInt64  `json:"parentId"`
	Labels           sql.NullString `json:"labels"`
	StoryPoints      sql.NullInt64  `json:"storyPoints"`
	DueDate          sql.NullTime   `json:"dueDate"`
	ResolvedAt       sql.NullTime   `json:"resolvedAt"`
	CreatedAt        time.Time      `json:"createdAt"`
	UpdatedAt        time.Time      `json:"updatedAt"`
	ProjectKey       string         `json:"projectKey"`
	ProjectName      string         `json:"projectName"`
	ReporterUsername string         `json:"reporterUsername"`
}

func (q *Queries) ListIssuesByAssignee(ctx context.Context, assigneeID sql.NullInt64) ([]ListIssuesByAssigneeRow, error) {
	rows, err := q.db.QueryContext(ctx, listIssuesByAssignee, assigneeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssuesByAssigneeRow{}
	for rows.Next() {
		var i ListIssuesByAssigneeRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IssueNumber,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.IssueType,
			&i.Rank,
			&i.ReporterID,
			&i.AssigneeID,
			&i.ParentID,
			&i.Labels,
			&i.StoryPoints,
			&i.DueDate,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectKey,
			&i.ProjectName,
			&i.ReporterUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesByProject = `-- name: ListIssuesByProject :many
SELECT 
    i.id, i.project_id, i.issue_number, i.title, i.description, i.status, i.priority, i.issue_type, i.rank, i.reporter_id, i.assignee_id, i.parent_id, i.labels, i.story_points, i.due_date, i.resolved_at, i.created_at, i.updated_at,
    p.key as project_key,
    r.username as reporter_username,
    r.full_name as reporter_full_name,
    a.username as assignee_username,
    a.full_name as assignee_full_name
FROM issues i
JOIN projects p ON i.project_id = p.id
JOIN users r ON i.reporter_id = r.id
LEFT JOIN users a ON i.assignee_id = a.id
WHERE i.project_id = ?
ORDER BY i.status, i.rank, i.created_at DESC
`

type ListIssuesByProjectRow struct {
	ID               int64          `json:"id"`
	ProjectID        int64          `json:"projectId"`
	IssueNumber      int64          `json:"issueNumber"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	Status           string         `json:"status"`
	Priority         string         `json:"priority"`
	IssueType        string         `json:"issueType"`
	Rank             string         `json:"rank"`
	ReporterID       int64          `json:"reporterId"`
	AssigneeID       sql.NullInt64  `json:"assigneeId"`
	ParentID         sql.NullInt64  `json:"parentId"`
	Labels           sql.NullString `json:"labels"`
	StoryPoints      sql.NullInt64  `json:"storyPoints"`
	DueDate          sql.NullTime   `json:"dueDate"`
	ResolvedAt       sql.NullTime   `json:"resolvedAt"`
	CreatedAt        time.Time      `json:"createdAt"`
	UpdatedAt        time.Time      `json:"updatedAt"`
	ProjectKey       string         `json:"projectKey"`
	ReporterUsername string         `json:"reporterUsername"`
	ReporterFullName string         `json:"reporterFullName"`
	AssigneeUsername sql.NullString `json:"assigneeUsername"`
	AssigneeFullName sql.NullString `json:"assigneeFullName"`
}

func (q *Queries) ListIssuesByProject(ctx context.Context, projectID int64) ([]ListIssuesByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listIssuesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssuesByProjectRow{}
	for rows.Next() {
		var i ListIssuesByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IssueNumber,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.IssueType,
			&i.Rank,
			&i.ReporterID,
			&i.AssigneeID,
			&i.ParentID,
			&i.Labels,
			&i.StoryPoints,
			&i.DueDate,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectKey,
			&i.ReporterUsername,
			&i.ReporterFullName,
			&i.AssigneeUsername,
			&i.AssigneeFullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesByStatus = `-- name: ListIssuesByStatus :many
SELECT 
    i.id, i.project_id, i.issue_number, i.title, i.description, i.status, i.priority, i.issue_type, i.rank, i.reporter_id, i.assignee_id, i.parent_id, i.labels, i.story_points, i.due_date, i.resolved_at, i.created_at, i.updated_at,
    p.key as project_key,
    r.username as reporter_username,
    a.username as assignee_username
FROM issues i
JOIN projects p ON i.project_id = p.id
JOIN users r ON i.reporter_id = r.id
LEFT JOIN users a ON i.assignee_id = a.id
WHERE i.project_id = ? AND i.status = ?
ORDER BY i.rank, i.created_at DESC
`

type ListIssuesByStatusParams struct {
	ProjectID int64  `json:"projectId"`
	Status    string `json:"status"`
}

type ListIssuesByStatusRow struct {
	ID               int64          `json:"id"`
	ProjectID        int64          `json:"projectId"`
	IssueNumber      int64          `json:"issueNumber"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	Status           string         `json:"status"`
	Priority         string         `json:"priority"`
	IssueType        string         `json:"issueType"`
	Rank             string         `json:"rank"`
	ReporterID       int64          `json:"reporterId"`
	AssigneeID       sql.NullInt64  `json:"assigneeId"`
	ParentID         sql.NullInt64  `json:"parentId"`
	Labels           sql.NullString `json:"labels"`
	StoryPoints      sql.NullInt64  `json:"storyPoints"`
	DueDate          sql.NullTime   `json:"dueDate"`
	ResolvedAt       sql.NullTime   `json:"resolvedAt"`
	CreatedAt        time.Time      `json:"createdAt"`
	UpdatedAt        time.Time      `json:"updatedAt"`
	ProjectKey       string         `json:"projectKey"`
	ReporterUsername string         `json:"reporterUsername"`
	AssigneeUsername sql.NullString `json:"assigneeUsername"`
}

// For Kanban board: get all issues in a status column, ordered by rank
func (q *Queries) ListIssuesByStatus(ctx context.Context, arg ListIssuesByStatusParams) ([]ListIssuesByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listIssuesByStatus, arg.ProjectID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssuesByStatusRow{}
	for rows.Next() {
		var i ListIssuesByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IssueNumber,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.IssueType,
			&i.Rank,
			&i.ReporterID,
			&i.AssigneeID,
			&i.ParentID,
			&i.Labels,
			&i.StoryPoints,
			&i.DueDate,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectKey,
			&i.ReporterUsername,
			&i.AssigneeUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentIssues = `-- name: ListRecentIssues :many
SELECT 
    i.id, i.project_id, i.issue_number, i.title, i.description, i.status, i.priority, i.issue_type, i.rank, i.reporter_id, i.assignee_id, i.parent_id, i.labels, i.story_points, i.due_date, i.resolved_at, i.created_at, i.updated_at,
    p.key as project_key,
    r.username as reporter_username,
    a.username as assignee_username
FROM issues i
JOIN projects p ON i.project_id = p.id
JOIN users r ON i.reporter_id = r.id
LEFT JOIN users a ON i.assignee_id = a.id
ORDER BY i.updated_at DESC
LIMIT ?
`

type ListRecentIssuesRow struct {
	ID               int64          `json:"id"`
	ProjectID        int64          `json:"projectId"`
	IssueNumber      int64          `json:"issueNumber"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	Status           string         `json:"status"`
	Priority         string         `json:"priority"`
	IssueType        string         `json:"issueType"`
	Rank             string         `json:"rank"`
	ReporterID       int64          `json:"reporterId"`
	AssigneeID       sql.NullInt64  `json:"assigneeId"`
	ParentID         sql.NullInt64  `json:"parentId"`
	Labels           sql.NullString `json:"labels"`
	StoryPoints      sql.NullInt64  `json:"storyPoints"`
	DueDate          sql.NullTime   `json:"dueDate"`
	ResolvedAt       sql.NullTime   `json:"resolvedAt"`
	CreatedAt        time.Time      `json:"createdAt"`
	UpdatedAt        time.Time      `json:"updatedAt"`
	ProjectKey       string         `json:"projectKey"`
	ReporterUsername string         `json:"reporterUsername"`
	AssigneeUsername sql.NullString `json:"assigneeUsername"`
}

func (q *Queries) ListRecentIssues(ctx context.Context, limit int64) ([]ListRecentIssuesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentIssues, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentIssuesRow{}
	for rows.Next() {
		var i ListRecentIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IssueNumber,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.IssueType,
			&i.Rank,
			&i.ReporterID,
			&i.AssigneeID,
			&i.ParentID,
			&i.Labels,
			&i.StoryPoints,
			&i.DueDate,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectKey,
			&i.ReporterUsername,
			&i.AssigneeUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchIssues = `-- name: SearchIssues :many
SELECT 
    i.id, i.project_id, i.issue_number, i.title, i.description, i.status, i.priority, i.issue_type, i.rank, i.reporter_id, i.assignee_id, i.parent_id, i.labels, i.story_points, i.due_date, i.resolved_at, i.created_at, i.updated_at,
    p.key as project_key,
    r.username as reporter_username,
    a.username as assignee_username
FROM issues i
JOIN projects p ON i.project_id = p.id
JOIN users r ON i.reporter_id = r.id
LEFT JOIN users a ON i.assignee_id = a.id
WHERE i.title LIKE '%' || ? || '%' OR i.description LIKE '%' || ? || '%'
ORDER BY i.updated_at DESC
LIMIT ?
`

type SearchIssuesParams struct {
	Column1 sql.NullString `json:"column1"`
	Column2 sql.NullString `json:"column2"`
	Limit   int64          `json:"limit"`
}

type SearchIssuesRow struct {
	ID               int64          `json:"id"`
	ProjectID        int64          `json:"projectId"`
	IssueNumber      int64          `json:"issueNumber"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	Status           string         `json:"status"`
	Priority         string         `json:"priority"`
	IssueType        string         `json:"issueType"`
	Rank             string         `json:"rank"`
	ReporterID       int64          `json:"reporterId"`
	AssigneeID       sql.NullInt64  `json:"assigneeId"`
	ParentID         sql.NullInt64  `json:"parentId"`
	Labels           sql.NullString `json:"labels"`
	StoryPoints      sql.NullInt64  `json:"storyPoints"`
	DueDate          sql.NullTime   `json:"dueDate"`
	ResolvedAt       sql.NullTime   `json:"resolvedAt"`
	CreatedAt        time.Time      `json:"createdAt"`
	UpdatedAt        time.Time      `json:"updatedAt"`
	ProjectKey       string         `json:"projectKey"`
	ReporterUsername string         `json:"reporterUsername"`
	AssigneeUsername sql.NullString `json:"assigneeUsername"`
}

func (q *Queries) SearchIssues(ctx context.Context, arg SearchIssuesParams) ([]SearchIssuesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchIssues, arg.Column1, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchIssuesRow{}
	for rows.Next() {
		var i SearchIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IssueNumber,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.IssueType,
			&i.Rank,
			&i.ReporterID,
			&i.AssigneeID,
			&i.ParentID,
			&i.Labels,
			&i.StoryPoints,
			&i.DueDate,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectKey,
			&i.ReporterUsername,
			&i.AssigneeUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIssue = `-- name: UpdateIssue :one
UPDATE issues SET
    title = COALESCE(?, title),
    description = COALESCE(?, description),
    priority = COALESCE(?, priority),
    issue_type = COALESCE(?, issue_type),
    assignee_id = ?,
    labels = COALESCE(?, labels),
    story_points = ?,
    due_date = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, project_id, issue_number, title, description, status, priority, issue_type, rank, reporter_id, assignee_id, parent_id, labels, story_points, due_date, resolved_at, created_at, updated_at
`

type UpdateIssueParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Priority    string         `json:"priority"`
	IssueType   string         `json:"issueType"`
	AssigneeID  sql.NullInt64  `json:"assigneeId"`
	Labels      sql.NullString `json:"labels"`
	StoryPoints sql.NullInt64  `json:"storyPoints"`
	DueDate     sql.NullTime   `json:"dueDate"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateIssue(ctx context.Context, arg UpdateIssueParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, updateIssue,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.IssueType,
		arg.AssigneeID,
		arg.Labels,
		arg.StoryPoints,
		arg.DueDate,
		arg.ID,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IssueNumber,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.IssueType,
		&i.Rank,
		&i.ReporterID,
		&i.AssigneeID,
		&i.ParentID,
		&i.Labels,
		&i.StoryPoints,
		&i.DueDate,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIssueRank = `-- name: UpdateIssueRank :exec
UPDATE issues SET rank = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateIssueRankParams struct {
	Rank string `json:"rank"`
	ID   int64  `json:"id"`
}

// Just update rank within same column
func (q *Queries) UpdateIssueRank(ctx context.Context, arg UpdateIssueRankParams) error {
	_, err := q.db.ExecContext(ctx, updateIssueRank, arg.Rank, arg.ID)
	return err
}

const updateIssueStatus = `-- name: UpdateIssueStatus :one
UPDATE issues SET
    status = ?,
    rank = ?,
    resolved_at = CASE WHEN ? = 'baked' THEN CURRENT_TIMESTAMP ELSE NULL END,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, project_id, issue_number, title, description, status, priority, issue_type, rank, reporter_id, assignee_id, parent_id, labels, story_points, due_date, resolved_at, created_at, updated_at
`

type UpdateIssueStatusParams struct {
	Status  string      `json:"status"`
	Rank    string      `json:"rank"`
	Column3 interface{} `json:"column3"`
	ID      int64       `json:"id"`
}

// Update status and rank (for Kanban drag-and-drop)
func (q *Queries) UpdateIssueStatus(ctx context.Context, arg UpdateIssueStatusParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, updateIssueStatus,
		arg.Status,
		arg.Rank,
		arg.Column3,
		arg.ID,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IssueNumber,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.IssueType,
		&i.Rank,
		&i.ReporterID,
		&i.AssigneeID,
		&i.ParentID,
		&i.Labels,
		&i.StoryPoints,
		&i.DueDate,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
