// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issue_comments.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countCommentsByIssue = `-- name: CountCommentsByIssue :one
SELECT COUNT(*) FROM issue_comments WHERE issue_id = ?
`

func (q *Queries) CountCommentsByIssue(ctx context.Context, issueID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCommentsByIssue, issueID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO issue_comments (issue_id, author_id, content)
VALUES (?, ?, ?)
RETURNING id, issue_id, author_id, content, created_at, updated_at
`

type CreateCommentParams struct {
	IssueID  int64  `json:"issueId"`
	AuthorID int64  `json:"authorId"`
	Content  string `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (IssueComment, error) {
	row := q.db.QueryRowContext(ctx, createComment, arg.IssueID, arg.AuthorID, arg.Content)
	var i IssueComment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM issue_comments WHERE id = ?
`

func (q *Queries) DeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const deleteCommentByAuthor = `-- name: DeleteCommentByAuthor :execrows
DELETE FROM issue_comments WHERE id = ? AND author_id = ?
`

type DeleteCommentByAuthorParams struct {
	ID       int64 `json:"id"`
	AuthorID int64 `json:"authorId"`
}

// Only allow author to delete their own comment
func (q *Queries) DeleteCommentByAuthor(ctx context.Context, arg DeleteCommentByAuthorParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCommentByAuthor, arg.ID, arg.AuthorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCommentByID = `-- name: GetCommentByID :one

SELECT c.id, c.issue_id, c.author_id, c.content, c.created_at, c.updated_at, u.username as author_username, u.full_name as author_full_name, u.avatar_url as author_avatar
FROM issue_comments c
JOIN users u ON c.author_id = u.id
WHERE c.id = ? LIMIT 1
`

type GetCommentByIDRow struct {
	ID             int64          `json:"id"`
	IssueID        int64          `json:"issueId"`
	AuthorID       int64          `json:"authorId"`
	Content        string         `json:"content"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	AuthorUsername string         `json:"authorUsername"`
	AuthorFullName string         `json:"authorFullName"`
	AuthorAvatar   sql.NullString `json:"authorAvatar"`
}

// ============================================
// Issue Comment Queries
// ============================================
func (q *Queries) GetCommentByID(ctx context.Context, id int64) (GetCommentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCommentByID, id)
	var i GetCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorUsername,
		&i.AuthorFullName,
		&i.AuthorAvatar,
	)
	return i, err
}

const listCommentsByIssue = `-- name: ListCommentsByIssue :many
SELECT c.id, c.issue_id, c.author_id, c.content, c.created_at, c.updated_at, u.username as author_username, u.full_name as author_full_name, u.avatar_url as author_avatar
FROM issue_comments c
JOIN users u ON c.author_id = u.id
WHERE c.issue_id = ?
ORDER BY c.created_at ASC
`

type ListCommentsByIssueRow struct {
	ID             int64          `json:"id"`
	IssueID        int64          `json:"issueId"`
	AuthorID       int64          `json:"authorId"`
	Content        string         `json:"content"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	AuthorUsername string         `json:"authorUsername"`
	AuthorFullName string         `json:"authorFullName"`
	AuthorAvatar   sql.NullString `json:"authorAvatar"`
}

func (q *Queries) ListCommentsByIssue(ctx context.Context, issueID int64) ([]ListCommentsByIssueRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsByIssueRow{}
	for rows.Next() {
		var i ListCommentsByIssueRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.AuthorFullName,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE issue_comments 
SET content = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND author_id = ?
RETURNING id, issue_id, author_id, content, created_at, updated_at
`

type UpdateCommentParams struct {
	Content  string `json:"content"`
	ID       int64  `json:"id"`
	AuthorID int64  `json:"authorId"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (IssueComment, error) {
	row := q.db.QueryRowContext(ctx, updateComment, arg.Content, arg.ID, arg.AuthorID)
	var i IssueComment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
