// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type ActivityLog struct {
	ID         int64          `json:"id"`
	UserID     sql.NullInt64  `json:"userId"`
	Action     string         `json:"action"`
	EntityType string         `json:"entityType"`
	EntityID   int64          `json:"entityId"`
	Metadata   sql.NullString `json:"metadata"`
	CreatedAt  time.Time      `json:"createdAt"`
}

type Doc struct {
	ID           int64          `json:"id"`
	ProjectID    sql.NullInt64  `json:"projectId"`
	Slug         string         `json:"slug"`
	Title        string         `json:"title"`
	Content      sql.NullString `json:"content"`
	ParentID     sql.NullInt64  `json:"parentId"`
	SortOrder    int64          `json:"sortOrder"`
	AuthorID     int64          `json:"authorId"`
	LastEditorID sql.NullInt64  `json:"lastEditorId"`
	IsPublished  bool           `json:"isPublished"`
	CreatedAt    time.Time      `json:"createdAt"`
	UpdatedAt    time.Time      `json:"updatedAt"`
}

type DocComment struct {
	ID        int64     `json:"id"`
	DocID     int64     `json:"docId"`
	AuthorID  int64     `json:"authorId"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Issue struct {
	ID          int64          `json:"id"`
	ProjectID   int64          `json:"projectId"`
	IssueNumber int64          `json:"issueNumber"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	Priority    string         `json:"priority"`
	IssueType   string         `json:"issueType"`
	Rank        string         `json:"rank"`
	ReporterID  int64          `json:"reporterId"`
	AssigneeID  sql.NullInt64  `json:"assigneeId"`
	ParentID    sql.NullInt64  `json:"parentId"`
	Labels      sql.NullString `json:"labels"`
	StoryPoints sql.NullInt64  `json:"storyPoints"`
	DueDate     sql.NullTime   `json:"dueDate"`
	ResolvedAt  sql.NullTime   `json:"resolvedAt"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
}

type IssueComment struct {
	ID        int64     `json:"id"`
	IssueID   int64     `json:"issueId"`
	AuthorID  int64     `json:"authorId"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Notification struct {
	ID               int64          `json:"id"`
	UserID           int64          `json:"userId"`
	ActorID          int64          `json:"actorId"`
	NotificationType string         `json:"notificationType"`
	EntityType       string         `json:"entityType"`
	EntityID         int64          `json:"entityId"`
	CommentID        sql.NullInt64  `json:"commentId"`
	Title            string         `json:"title"`
	Message          string         `json:"message"`
	IsRead           bool           `json:"isRead"`
	ReadAt           sql.NullTime   `json:"readAt"`
	CreatedAt        time.Time      `json:"createdAt"`
	MessageKey       sql.NullString `json:"messageKey"`
	MessageParams    sql.NullString `json:"messageParams"`
}

type Project struct {
	ID          int64          `json:"id"`
	Key         string         `json:"key"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	LeadID      sql.NullInt64  `json:"leadId"`
	IsArchived  bool           `json:"isArchived"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
}

type Release struct {
	ID           int64          `json:"id"`
	ProjectID    sql.NullInt64  `json:"projectId"`
	Version      string         `json:"version"`
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	AuthorID     int64          `json:"authorId"`
	IsDraft      bool           `json:"isDraft"`
	IsPrerelease bool           `json:"isPrerelease"`
	PublishedAt  sql.NullTime   `json:"publishedAt"`
	CreatedAt    time.Time      `json:"createdAt"`
	UpdatedAt    time.Time      `json:"updatedAt"`
}

type ReleaseComment struct {
	ID        int64     `json:"id"`
	ReleaseID int64     `json:"releaseId"`
	AuthorID  int64     `json:"authorId"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type ReleaseFile struct {
	ID               int64          `json:"id"`
	ReleaseID        int64          `json:"releaseId"`
	Filename         string         `json:"filename"`
	OriginalFilename string         `json:"originalFilename"`
	FilePath         string         `json:"filePath"`
	FileSize         int64          `json:"fileSize"`
	MimeType         string         `json:"mimeType"`
	Sha256Hash       sql.NullString `json:"sha256Hash"`
	DownloadCount    int64          `json:"downloadCount"`
	CreatedAt        time.Time      `json:"createdAt"`
}

type Session struct {
	ID        int64          `json:"id"`
	UserID    int64          `json:"userId"`
	Token     string         `json:"token"`
	UserAgent sql.NullString `json:"userAgent"`
	IpAddress sql.NullString `json:"ipAddress"`
	ExpiresAt time.Time      `json:"expiresAt"`
	CreatedAt time.Time      `json:"createdAt"`
}

type User struct {
	ID           int64          `json:"id"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"passwordHash"`
	FullName     string         `json:"fullName"`
	AvatarUrl    sql.NullString `json:"avatarUrl"`
	IsActive     bool           `json:"isActive"`
	CreatedAt    time.Time      `json:"createdAt"`
	UpdatedAt    time.Time      `json:"updatedAt"`
}
