// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications 
WHERE user_id = ? AND is_read = 0
`

// Get count of unread notifications for badge display
func (q *Queries) CountUnreadNotifications(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    user_id, actor_id, notification_type, entity_type, entity_id,
    comment_id, title, message
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, actor_id, notification_type, entity_type, entity_id, comment_id, title, message, is_read, read_at, created_at
`

type CreateNotificationParams struct {
	UserID           int64         `json:"userId"`
	ActorID          int64         `json:"actorId"`
	NotificationType string        `json:"notificationType"`
	EntityType       string        `json:"entityType"`
	EntityID         int64         `json:"entityId"`
	CommentID        sql.NullInt64 `json:"commentId"`
	Title            string        `json:"title"`
	Message          string        `json:"message"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.UserID,
		arg.ActorID,
		arg.NotificationType,
		arg.EntityType,
		arg.EntityID,
		arg.CommentID,
		arg.Title,
		arg.Message,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActorID,
		&i.NotificationType,
		&i.EntityType,
		&i.EntityID,
		&i.CommentID,
		&i.Title,
		&i.Message,
		&i.IsRead,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications WHERE id = ? AND user_id = ?
`

type DeleteNotificationParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"userId"`
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error {
	_, err := q.db.ExecContext(ctx, deleteNotification, arg.ID, arg.UserID)
	return err
}

const getAllActiveUserIDs = `-- name: GetAllActiveUserIDs :many
SELECT id FROM users WHERE is_active = 1
`

// Get all active user IDs for @everyone mention notifications
func (q *Queries) GetAllActiveUserIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getAllActiveUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocOwner = `-- name: GetDocOwner :one
SELECT 
    d.author_id,
    d.title
FROM docs d
WHERE d.id = ?
LIMIT 1
`

type GetDocOwnerRow struct {
	AuthorID int64  `json:"authorId"`
	Title    string `json:"title"`
}

// Get author for a doc (for notification recipients)
func (q *Queries) GetDocOwner(ctx context.Context, id int64) (GetDocOwnerRow, error) {
	row := q.db.QueryRowContext(ctx, getDocOwner, id)
	var i GetDocOwnerRow
	err := row.Scan(&i.AuthorID, &i.Title)
	return i, err
}

const getIssueOwnerAndAssignee = `-- name: GetIssueOwnerAndAssignee :one
SELECT 
    i.reporter_id,
    i.assignee_id,
    i.title,
    p.key as project_key,
    i.issue_number
FROM issues i
JOIN projects p ON i.project_id = p.id
WHERE i.id = ?
LIMIT 1
`

type GetIssueOwnerAndAssigneeRow struct {
	ReporterID  int64         `json:"reporterId"`
	AssigneeID  sql.NullInt64 `json:"assigneeId"`
	Title       string        `json:"title"`
	ProjectKey  string        `json:"projectKey"`
	IssueNumber int64         `json:"issueNumber"`
}

// Get reporter and assignee for an issue (for notification recipients)
func (q *Queries) GetIssueOwnerAndAssignee(ctx context.Context, id int64) (GetIssueOwnerAndAssigneeRow, error) {
	row := q.db.QueryRowContext(ctx, getIssueOwnerAndAssignee, id)
	var i GetIssueOwnerAndAssigneeRow
	err := row.Scan(
		&i.ReporterID,
		&i.AssigneeID,
		&i.Title,
		&i.ProjectKey,
		&i.IssueNumber,
	)
	return i, err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT 
    n.id, n.user_id, n.actor_id, n.notification_type, n.entity_type, n.entity_id, n.comment_id, n.title, n.message, n.is_read, n.read_at, n.created_at,
    u.username as actor_username,
    u.full_name as actor_full_name,
    u.avatar_url as actor_avatar
FROM notifications n
JOIN users u ON n.actor_id = u.id
WHERE n.id = ? AND n.user_id = ?
LIMIT 1
`

type GetNotificationByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"userId"`
}

type GetNotificationByIDRow struct {
	ID               int64          `json:"id"`
	UserID           int64          `json:"userId"`
	ActorID          int64          `json:"actorId"`
	NotificationType string         `json:"notificationType"`
	EntityType       string         `json:"entityType"`
	EntityID         int64          `json:"entityId"`
	CommentID        sql.NullInt64  `json:"commentId"`
	Title            string         `json:"title"`
	Message          string         `json:"message"`
	IsRead           bool           `json:"isRead"`
	ReadAt           sql.NullTime   `json:"readAt"`
	CreatedAt        time.Time      `json:"createdAt"`
	ActorUsername    string         `json:"actorUsername"`
	ActorFullName    string         `json:"actorFullName"`
	ActorAvatar      sql.NullString `json:"actorAvatar"`
}

func (q *Queries) GetNotificationByID(ctx context.Context, arg GetNotificationByIDParams) (GetNotificationByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getNotificationByID, arg.ID, arg.UserID)
	var i GetNotificationByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActorID,
		&i.NotificationType,
		&i.EntityType,
		&i.EntityID,
		&i.CommentID,
		&i.Title,
		&i.Message,
		&i.IsRead,
		&i.ReadAt,
		&i.CreatedAt,
		&i.ActorUsername,
		&i.ActorFullName,
		&i.ActorAvatar,
	)
	return i, err
}

const getReleaseOwner = `-- name: GetReleaseOwner :one
SELECT
    r.author_id,
    r.title,
    r.version
FROM releases r
WHERE r.id = ?
LIMIT 1
`

type GetReleaseOwnerRow struct {
	AuthorID int64  `json:"authorId"`
	Title    string `json:"title"`
	Version  string `json:"version"`
}

// Get author for a release (for notification recipients)
func (q *Queries) GetReleaseOwner(ctx context.Context, id int64) (GetReleaseOwnerRow, error) {
	row := q.db.QueryRowContext(ctx, getReleaseOwner, id)
	var i GetReleaseOwnerRow
	err := row.Scan(&i.AuthorID, &i.Title, &i.Version)
	return i, err
}

const getUserIDByUsername = `-- name: GetUserIDByUsername :one
SELECT id FROM users 
WHERE username = ? COLLATE NOCASE
LIMIT 1
`

// For @mention lookup - find user by username
func (q *Queries) GetUserIDByUsername(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByUsername, username)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many

SELECT 
    n.id, n.user_id, n.actor_id, n.notification_type, n.entity_type, n.entity_id, n.comment_id, n.title, n.message, n.is_read, n.read_at, n.created_at,
    u.username as actor_username,
    u.full_name as actor_full_name,
    u.avatar_url as actor_avatar
FROM notifications n
JOIN users u ON n.actor_id = u.id
WHERE n.user_id = ?
ORDER BY n.created_at DESC
LIMIT ?
`

type ListNotificationsByUserParams struct {
	UserID int64 `json:"userId"`
	Limit  int64 `json:"limit"`
}

type ListNotificationsByUserRow struct {
	ID               int64          `json:"id"`
	UserID           int64          `json:"userId"`
	ActorID          int64          `json:"actorId"`
	NotificationType string         `json:"notificationType"`
	EntityType       string         `json:"entityType"`
	EntityID         int64          `json:"entityId"`
	CommentID        sql.NullInt64  `json:"commentId"`
	Title            string         `json:"title"`
	Message          string         `json:"message"`
	IsRead           bool           `json:"isRead"`
	ReadAt           sql.NullTime   `json:"readAt"`
	CreatedAt        time.Time      `json:"createdAt"`
	ActorUsername    string         `json:"actorUsername"`
	ActorFullName    string         `json:"actorFullName"`
	ActorAvatar      sql.NullString `json:"actorAvatar"`
}

// ============================================
// Notification Queries
// ============================================
// Get all notifications for a user, ordered by most recent first
// Includes actor information for display
func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]ListNotificationsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsByUserRow{}
	for rows.Next() {
		var i ListNotificationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActorID,
			&i.NotificationType,
			&i.EntityType,
			&i.EntityID,
			&i.CommentID,
			&i.Title,
			&i.Message,
			&i.IsRead,
			&i.ReadAt,
			&i.CreatedAt,
			&i.ActorUsername,
			&i.ActorFullName,
			&i.ActorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications 
SET is_read = 1, read_at = CURRENT_TIMESTAMP
WHERE user_id = ? AND is_read = 0
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAllNotificationsRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications 
SET is_read = 1, read_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
RETURNING id, user_id, actor_id, notification_type, entity_type, entity_id, comment_id, title, message, is_read, read_at, created_at
`

type MarkNotificationReadParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"userId"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, markNotificationRead, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActorID,
		&i.NotificationType,
		&i.EntityType,
		&i.EntityID,
		&i.CommentID,
		&i.Title,
		&i.Message,
		&i.IsRead,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}
