// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const archiveProject = `-- name: ArchiveProject :exec
UPDATE projects SET is_archived = 1, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) ArchiveProject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, archiveProject, id)
	return err
}

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*) FROM projects WHERE is_archived = 0
`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (key, name, description, lead_id)
VALUES (?, ?, ?, ?)
RETURNING id, "key", name, description, lead_id, is_archived, created_at, updated_at
`

type CreateProjectParams struct {
	Key         string         `json:"key"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	LeadID      sql.NullInt64  `json:"leadId"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.LeadID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.LeadID,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one

SELECT p.id, p."key", p.name, p.description, p.lead_id, p.is_archived, p.created_at, p.updated_at, u.username as lead_username, u.full_name as lead_full_name
FROM projects p
LEFT JOIN users u ON p.lead_id = u.id
WHERE p.id = ? LIMIT 1
`

type GetProjectByIDRow struct {
	ID           int64          `json:"id"`
	Key          string         `json:"key"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	LeadID       sql.NullInt64  `json:"leadId"`
	IsArchived   bool           `json:"isArchived"`
	CreatedAt    time.Time      `json:"createdAt"`
	UpdatedAt    time.Time      `json:"updatedAt"`
	LeadUsername sql.NullString `json:"leadUsername"`
	LeadFullName sql.NullString `json:"leadFullName"`
}

// ============================================
// Project Queries
// ============================================
func (q *Queries) GetProjectByID(ctx context.Context, id int64) (GetProjectByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i GetProjectByIDRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.LeadID,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LeadUsername,
		&i.LeadFullName,
	)
	return i, err
}

const getProjectByKey = `-- name: GetProjectByKey :one
SELECT p.id, p."key", p.name, p.description, p.lead_id, p.is_archived, p.created_at, p.updated_at, u.username as lead_username, u.full_name as lead_full_name
FROM projects p
LEFT JOIN users u ON p.lead_id = u.id
WHERE p.key = ? COLLATE NOCASE LIMIT 1
`

type GetProjectByKeyRow struct {
	ID           int64          `json:"id"`
	Key          string         `json:"key"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	LeadID       sql.NullInt64  `json:"leadId"`
	IsArchived   bool           `json:"isArchived"`
	CreatedAt    time.Time      `json:"createdAt"`
	UpdatedAt    time.Time      `json:"updatedAt"`
	LeadUsername sql.NullString `json:"leadUsername"`
	LeadFullName sql.NullString `json:"leadFullName"`
}

func (q *Queries) GetProjectByKey(ctx context.Context, key string) (GetProjectByKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectByKey, key)
	var i GetProjectByKeyRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.LeadID,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LeadUsername,
		&i.LeadFullName,
	)
	return i, err
}

const listAllProjects = `-- name: ListAllProjects :many
SELECT p.id, p."key", p.name, p.description, p.lead_id, p.is_archived, p.created_at, p.updated_at, u.username as lead_username, u.full_name as lead_full_name
FROM projects p
LEFT JOIN users u ON p.lead_id = u.id
ORDER BY p.is_archived, p.name
`

type ListAllProjectsRow struct {
	ID           int64          `json:"id"`
	Key          string         `json:"key"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	LeadID       sql.NullInt64  `json:"leadId"`
	IsArchived   bool           `json:"isArchived"`
	CreatedAt    time.Time      `json:"createdAt"`
	UpdatedAt    time.Time      `json:"updatedAt"`
	LeadUsername sql.NullString `json:"leadUsername"`
	LeadFullName sql.NullString `json:"leadFullName"`
}

func (q *Queries) ListAllProjects(ctx context.Context) ([]ListAllProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllProjectsRow{}
	for rows.Next() {
		var i ListAllProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.LeadID,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LeadUsername,
			&i.LeadFullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT p.id, p."key", p.name, p.description, p.lead_id, p.is_archived, p.created_at, p.updated_at, u.username as lead_username, u.full_name as lead_full_name
FROM projects p
LEFT JOIN users u ON p.lead_id = u.id
WHERE p.is_archived = 0
ORDER BY p.name
`

type ListProjectsRow struct {
	ID           int64          `json:"id"`
	Key          string         `json:"key"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	LeadID       sql.NullInt64  `json:"leadId"`
	IsArchived   bool           `json:"isArchived"`
	CreatedAt    time.Time      `json:"createdAt"`
	UpdatedAt    time.Time      `json:"updatedAt"`
	LeadUsername sql.NullString `json:"leadUsername"`
	LeadFullName sql.NullString `json:"leadFullName"`
}

func (q *Queries) ListProjects(ctx context.Context) ([]ListProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.LeadID,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LeadUsername,
			&i.LeadFullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unarchiveProject = `-- name: UnarchiveProject :exec
UPDATE projects SET is_archived = 0, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) UnarchiveProject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, unarchiveProject, id)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects 
SET name = ?, description = ?, lead_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, "key", name, description, lead_id, is_archived, created_at, updated_at
`

type UpdateProjectParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	LeadID      sql.NullInt64  `json:"leadId"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.LeadID,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.LeadID,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
