// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	ActivateUser(ctx context.Context, id int64) error
	ArchiveProject(ctx context.Context, id int64) error
	CountActivityByUser(ctx context.Context, userID sql.NullInt64) (int64, error)
	CountCommentsByIssue(ctx context.Context, issueID int64) (int64, error)
	CountDocs(ctx context.Context) (int64, error)
	CountDocsByProject(ctx context.Context, projectID sql.NullInt64) (int64, error)
	CountIssuesByProject(ctx context.Context, projectID int64) (int64, error)
	CountIssuesByStatus(ctx context.Context, arg CountIssuesByStatusParams) (int64, error)
	CountProjects(ctx context.Context) (int64, error)
	CountReleases(ctx context.Context) (int64, error)
	CountReleasesByProject(ctx context.Context, projectID sql.NullInt64) (int64, error)
	CountUserSessions(ctx context.Context, userID int64) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	// ============================================
	// Activity Log Queries
	// ============================================
	CreateActivity(ctx context.Context, arg CreateActivityParams) (ActivityLog, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (IssueComment, error)
	CreateDoc(ctx context.Context, arg CreateDocParams) (Doc, error)
	CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateRelease(ctx context.Context, arg CreateReleaseParams) (Release, error)
	CreateReleaseFile(ctx context.Context, arg CreateReleaseFileParams) (ReleaseFile, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateUser(ctx context.Context, id int64) error
	DeleteComment(ctx context.Context, id int64) error
	// Only allow author to delete their own comment
	DeleteCommentByAuthor(ctx context.Context, arg DeleteCommentByAuthorParams) error
	DeleteDoc(ctx context.Context, id int64) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteIssue(ctx context.Context, id int64) error
	// Clean up activity logs older than N days
	DeleteOldActivity(ctx context.Context, dollar_1 sql.NullString) error
	// Keep only the N most recent sessions per user
	DeleteOldestUserSessions(ctx context.Context, arg DeleteOldestUserSessionsParams) error
	DeleteProject(ctx context.Context, id int64) error
	DeleteRelease(ctx context.Context, id int64) error
	DeleteReleaseFile(ctx context.Context, id int64) error
	DeleteReleaseFiles(ctx context.Context, releaseID int64) error
	DeleteSession(ctx context.Context, token string) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserSessions(ctx context.Context, userID int64) error
	// ============================================
	// Issue Comment Queries
	// ============================================
	GetCommentByID(ctx context.Context, id int64) (GetCommentByIDRow, error)
	// ============================================
	// Doc Queries (The Library)
	// ============================================
	GetDocByID(ctx context.Context, id int64) (GetDocByIDRow, error)
	GetDocBySlug(ctx context.Context, slug string) (GetDocBySlugRow, error)
	// Recursive CTE to get full doc tree (SQLite 3.8.3+)
	GetDocTree(ctx context.Context) ([]GetDocTreeRow, error)
	// ============================================
	// Issue Queries (The Tablet)
	// ============================================
	GetIssueByID(ctx context.Context, id int64) (GetIssueByIDRow, error)
	GetIssueByProjectAndNumber(ctx context.Context, arg GetIssueByProjectAndNumberParams) (GetIssueByProjectAndNumberRow, error)
	GetLatestRelease(ctx context.Context, projectID sql.NullInt64) (GetLatestReleaseRow, error)
	// Get the highest rank in a status column for inserting at the end
	GetMaxRankInStatus(ctx context.Context, arg GetMaxRankInStatusParams) (interface{}, error)
	GetNextIssueNumber(ctx context.Context, projectID int64) (int64, error)
	// ============================================
	// Project Queries
	// ============================================
	GetProjectByID(ctx context.Context, id int64) (GetProjectByIDRow, error)
	GetProjectByKey(ctx context.Context, key string) (GetProjectByKeyRow, error)
	// ============================================
	// Release Queries (The Granary)
	// ============================================
	GetReleaseByID(ctx context.Context, id int64) (GetReleaseByIDRow, error)
	GetReleaseByVersion(ctx context.Context, arg GetReleaseByVersionParams) (GetReleaseByVersionRow, error)
	// ============================================
	// Release File Queries
	// ============================================
	GetReleaseFileByID(ctx context.Context, id int64) (ReleaseFile, error)
	GetReleaseFileByName(ctx context.Context, arg GetReleaseFileByNameParams) (ReleaseFile, error)
	// ============================================
	// Session Queries
	// ============================================
	GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error)
	GetTotalDownloads(ctx context.Context, releaseID int64) (interface{}, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// ============================================
	// User Queries
	// ============================================
	GetUserByID(ctx context.Context, id int64) (User, error)
	// Smart login: find user by username (case-insensitive)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// Used for smart login: accepts either username or full email
	GetUserByUsernameOrEmail(ctx context.Context, arg GetUserByUsernameOrEmailParams) (User, error)
	ListActivityByEntity(ctx context.Context, arg ListActivityByEntityParams) ([]ListActivityByEntityRow, error)
	ListActivityByUser(ctx context.Context, arg ListActivityByUserParams) ([]ListActivityByUserRow, error)
	// Include unpublished (for admin)
	ListAllDocs(ctx context.Context) ([]ListAllDocsRow, error)
	ListAllProjects(ctx context.Context) ([]ListAllProjectsRow, error)
	// Include drafts (for admin/author)
	ListAllReleases(ctx context.Context) ([]ListAllReleasesRow, error)
	ListAllUsers(ctx context.Context) ([]User, error)
	ListCommentsByIssue(ctx context.Context, issueID int64) ([]ListCommentsByIssueRow, error)
	// List all root-level docs (no parent)
	ListDocs(ctx context.Context) ([]ListDocsRow, error)
	// Get children of a doc (for tree navigation)
	ListDocsByParent(ctx context.Context, parentID sql.NullInt64) ([]ListDocsByParentRow, error)
	ListDocsByProject(ctx context.Context, projectID sql.NullInt64) ([]ListDocsByProjectRow, error)
	ListDraftReleases(ctx context.Context) ([]ListDraftReleasesRow, error)
	ListIssuesByAssignee(ctx context.Context, assigneeID sql.NullInt64) ([]ListIssuesByAssigneeRow, error)
	ListIssuesByProject(ctx context.Context, projectID int64) ([]ListIssuesByProjectRow, error)
	// For Kanban board: get all issues in a status column, ordered by rank
	ListIssuesByStatus(ctx context.Context, arg ListIssuesByStatusParams) ([]ListIssuesByStatusRow, error)
	ListProjects(ctx context.Context) ([]ListProjectsRow, error)
	ListRecentActivity(ctx context.Context, limit int64) ([]ListRecentActivityRow, error)
	ListRecentIssues(ctx context.Context, limit int64) ([]ListRecentIssuesRow, error)
	ListReleaseFiles(ctx context.Context, releaseID int64) ([]ReleaseFile, error)
	ListReleases(ctx context.Context) ([]ListReleasesRow, error)
	ListReleasesByProject(ctx context.Context, projectID sql.NullInt64) ([]ListReleasesByProjectRow, error)
	ListUserSessions(ctx context.Context, userID int64) ([]Session, error)
	ListUsers(ctx context.Context) ([]User, error)
	PublishRelease(ctx context.Context, id int64) (Release, error)
	SearchDocs(ctx context.Context, arg SearchDocsParams) ([]SearchDocsRow, error)
	SearchIssues(ctx context.Context, arg SearchIssuesParams) ([]SearchIssuesRow, error)
	UnarchiveProject(ctx context.Context, id int64) error
	UnpublishRelease(ctx context.Context, id int64) error
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (IssueComment, error)
	UpdateDoc(ctx context.Context, arg UpdateDocParams) (Doc, error)
	UpdateDocSlug(ctx context.Context, arg UpdateDocSlugParams) error
	UpdateIssue(ctx context.Context, arg UpdateIssueParams) (Issue, error)
	// Just update rank within same column
	UpdateIssueRank(ctx context.Context, arg UpdateIssueRankParams) error
	// Update status and rank (for Kanban drag-and-drop)
	UpdateIssueStatus(ctx context.Context, arg UpdateIssueStatusParams) (Issue, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateRelease(ctx context.Context, arg UpdateReleaseParams) (Release, error)
	UpdateReleaseFileDownloadCount(ctx context.Context, id int64) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
