// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reactions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createReactionOnDoc = `-- name: CreateReactionOnDoc :one
INSERT INTO reactions (user_id, emoji, doc_id)
VALUES (?, ?, ?)
RETURNING id, user_id, emoji, issue_id, doc_id, release_id, issue_comment_id, doc_comment_id, release_comment_id, created_at
`

type CreateReactionOnDocParams struct {
	UserID int64         `json:"userId"`
	Emoji  string        `json:"emoji"`
	DocID  sql.NullInt64 `json:"docId"`
}

func (q *Queries) CreateReactionOnDoc(ctx context.Context, arg CreateReactionOnDocParams) (Reaction, error) {
	row := q.db.QueryRowContext(ctx, createReactionOnDoc, arg.UserID, arg.Emoji, arg.DocID)
	var i Reaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Emoji,
		&i.IssueID,
		&i.DocID,
		&i.ReleaseID,
		&i.IssueCommentID,
		&i.DocCommentID,
		&i.ReleaseCommentID,
		&i.CreatedAt,
	)
	return i, err
}

const createReactionOnDocComment = `-- name: CreateReactionOnDocComment :one
INSERT INTO reactions (user_id, emoji, doc_comment_id)
VALUES (?, ?, ?)
RETURNING id, user_id, emoji, issue_id, doc_id, release_id, issue_comment_id, doc_comment_id, release_comment_id, created_at
`

type CreateReactionOnDocCommentParams struct {
	UserID       int64         `json:"userId"`
	Emoji        string        `json:"emoji"`
	DocCommentID sql.NullInt64 `json:"docCommentId"`
}

func (q *Queries) CreateReactionOnDocComment(ctx context.Context, arg CreateReactionOnDocCommentParams) (Reaction, error) {
	row := q.db.QueryRowContext(ctx, createReactionOnDocComment, arg.UserID, arg.Emoji, arg.DocCommentID)
	var i Reaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Emoji,
		&i.IssueID,
		&i.DocID,
		&i.ReleaseID,
		&i.IssueCommentID,
		&i.DocCommentID,
		&i.ReleaseCommentID,
		&i.CreatedAt,
	)
	return i, err
}

const createReactionOnIssue = `-- name: CreateReactionOnIssue :one
INSERT INTO reactions (user_id, emoji, issue_id)
VALUES (?, ?, ?)
RETURNING id, user_id, emoji, issue_id, doc_id, release_id, issue_comment_id, doc_comment_id, release_comment_id, created_at
`

type CreateReactionOnIssueParams struct {
	UserID  int64         `json:"userId"`
	Emoji   string        `json:"emoji"`
	IssueID sql.NullInt64 `json:"issueId"`
}

func (q *Queries) CreateReactionOnIssue(ctx context.Context, arg CreateReactionOnIssueParams) (Reaction, error) {
	row := q.db.QueryRowContext(ctx, createReactionOnIssue, arg.UserID, arg.Emoji, arg.IssueID)
	var i Reaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Emoji,
		&i.IssueID,
		&i.DocID,
		&i.ReleaseID,
		&i.IssueCommentID,
		&i.DocCommentID,
		&i.ReleaseCommentID,
		&i.CreatedAt,
	)
	return i, err
}

const createReactionOnIssueComment = `-- name: CreateReactionOnIssueComment :one
INSERT INTO reactions (user_id, emoji, issue_comment_id)
VALUES (?, ?, ?)
RETURNING id, user_id, emoji, issue_id, doc_id, release_id, issue_comment_id, doc_comment_id, release_comment_id, created_at
`

type CreateReactionOnIssueCommentParams struct {
	UserID         int64         `json:"userId"`
	Emoji          string        `json:"emoji"`
	IssueCommentID sql.NullInt64 `json:"issueCommentId"`
}

func (q *Queries) CreateReactionOnIssueComment(ctx context.Context, arg CreateReactionOnIssueCommentParams) (Reaction, error) {
	row := q.db.QueryRowContext(ctx, createReactionOnIssueComment, arg.UserID, arg.Emoji, arg.IssueCommentID)
	var i Reaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Emoji,
		&i.IssueID,
		&i.DocID,
		&i.ReleaseID,
		&i.IssueCommentID,
		&i.DocCommentID,
		&i.ReleaseCommentID,
		&i.CreatedAt,
	)
	return i, err
}

const createReactionOnRelease = `-- name: CreateReactionOnRelease :one
INSERT INTO reactions (user_id, emoji, release_id)
VALUES (?, ?, ?)
RETURNING id, user_id, emoji, issue_id, doc_id, release_id, issue_comment_id, doc_comment_id, release_comment_id, created_at
`

type CreateReactionOnReleaseParams struct {
	UserID    int64         `json:"userId"`
	Emoji     string        `json:"emoji"`
	ReleaseID sql.NullInt64 `json:"releaseId"`
}

func (q *Queries) CreateReactionOnRelease(ctx context.Context, arg CreateReactionOnReleaseParams) (Reaction, error) {
	row := q.db.QueryRowContext(ctx, createReactionOnRelease, arg.UserID, arg.Emoji, arg.ReleaseID)
	var i Reaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Emoji,
		&i.IssueID,
		&i.DocID,
		&i.ReleaseID,
		&i.IssueCommentID,
		&i.DocCommentID,
		&i.ReleaseCommentID,
		&i.CreatedAt,
	)
	return i, err
}

const createReactionOnReleaseComment = `-- name: CreateReactionOnReleaseComment :one
INSERT INTO reactions (user_id, emoji, release_comment_id)
VALUES (?, ?, ?)
RETURNING id, user_id, emoji, issue_id, doc_id, release_id, issue_comment_id, doc_comment_id, release_comment_id, created_at
`

type CreateReactionOnReleaseCommentParams struct {
	UserID           int64         `json:"userId"`
	Emoji            string        `json:"emoji"`
	ReleaseCommentID sql.NullInt64 `json:"releaseCommentId"`
}

func (q *Queries) CreateReactionOnReleaseComment(ctx context.Context, arg CreateReactionOnReleaseCommentParams) (Reaction, error) {
	row := q.db.QueryRowContext(ctx, createReactionOnReleaseComment, arg.UserID, arg.Emoji, arg.ReleaseCommentID)
	var i Reaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Emoji,
		&i.IssueID,
		&i.DocID,
		&i.ReleaseID,
		&i.IssueCommentID,
		&i.DocCommentID,
		&i.ReleaseCommentID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReactionFromDoc = `-- name: DeleteReactionFromDoc :execrows
DELETE FROM reactions 
WHERE user_id = ? AND emoji = ? AND doc_id = ?
`

type DeleteReactionFromDocParams struct {
	UserID int64         `json:"userId"`
	Emoji  string        `json:"emoji"`
	DocID  sql.NullInt64 `json:"docId"`
}

func (q *Queries) DeleteReactionFromDoc(ctx context.Context, arg DeleteReactionFromDocParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteReactionFromDoc, arg.UserID, arg.Emoji, arg.DocID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteReactionFromDocComment = `-- name: DeleteReactionFromDocComment :execrows
DELETE FROM reactions 
WHERE user_id = ? AND emoji = ? AND doc_comment_id = ?
`

type DeleteReactionFromDocCommentParams struct {
	UserID       int64         `json:"userId"`
	Emoji        string        `json:"emoji"`
	DocCommentID sql.NullInt64 `json:"docCommentId"`
}

func (q *Queries) DeleteReactionFromDocComment(ctx context.Context, arg DeleteReactionFromDocCommentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteReactionFromDocComment, arg.UserID, arg.Emoji, arg.DocCommentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteReactionFromIssue = `-- name: DeleteReactionFromIssue :execrows
DELETE FROM reactions 
WHERE user_id = ? AND emoji = ? AND issue_id = ?
`

type DeleteReactionFromIssueParams struct {
	UserID  int64         `json:"userId"`
	Emoji   string        `json:"emoji"`
	IssueID sql.NullInt64 `json:"issueId"`
}

func (q *Queries) DeleteReactionFromIssue(ctx context.Context, arg DeleteReactionFromIssueParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteReactionFromIssue, arg.UserID, arg.Emoji, arg.IssueID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteReactionFromIssueComment = `-- name: DeleteReactionFromIssueComment :execrows
DELETE FROM reactions 
WHERE user_id = ? AND emoji = ? AND issue_comment_id = ?
`

type DeleteReactionFromIssueCommentParams struct {
	UserID         int64         `json:"userId"`
	Emoji          string        `json:"emoji"`
	IssueCommentID sql.NullInt64 `json:"issueCommentId"`
}

func (q *Queries) DeleteReactionFromIssueComment(ctx context.Context, arg DeleteReactionFromIssueCommentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteReactionFromIssueComment, arg.UserID, arg.Emoji, arg.IssueCommentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteReactionFromRelease = `-- name: DeleteReactionFromRelease :execrows
DELETE FROM reactions 
WHERE user_id = ? AND emoji = ? AND release_id = ?
`

type DeleteReactionFromReleaseParams struct {
	UserID    int64         `json:"userId"`
	Emoji     string        `json:"emoji"`
	ReleaseID sql.NullInt64 `json:"releaseId"`
}

func (q *Queries) DeleteReactionFromRelease(ctx context.Context, arg DeleteReactionFromReleaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteReactionFromRelease, arg.UserID, arg.Emoji, arg.ReleaseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteReactionFromReleaseComment = `-- name: DeleteReactionFromReleaseComment :execrows
DELETE FROM reactions 
WHERE user_id = ? AND emoji = ? AND release_comment_id = ?
`

type DeleteReactionFromReleaseCommentParams struct {
	UserID           int64         `json:"userId"`
	Emoji            string        `json:"emoji"`
	ReleaseCommentID sql.NullInt64 `json:"releaseCommentId"`
}

func (q *Queries) DeleteReactionFromReleaseComment(ctx context.Context, arg DeleteReactionFromReleaseCommentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteReactionFromReleaseComment, arg.UserID, arg.Emoji, arg.ReleaseCommentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getIssueReactionCounts = `-- name: GetIssueReactionCounts :many
SELECT emoji, COUNT(*) as count
FROM reactions
WHERE issue_id = ?
GROUP BY emoji
ORDER BY count DESC
`

type GetIssueReactionCountsRow struct {
	Emoji string `json:"emoji"`
	Count int64  `json:"count"`
}

func (q *Queries) GetIssueReactionCounts(ctx context.Context, issueID sql.NullInt64) ([]GetIssueReactionCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getIssueReactionCounts, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetIssueReactionCountsRow{}
	for rows.Next() {
		var i GetIssueReactionCountsRow
		if err := rows.Scan(&i.Emoji, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReactionOnDoc = `-- name: GetReactionOnDoc :one
SELECT id, user_id, emoji, issue_id, doc_id, release_id, issue_comment_id, doc_comment_id, release_comment_id, created_at FROM reactions
WHERE user_id = ? AND emoji = ? AND doc_id = ?
LIMIT 1
`

type GetReactionOnDocParams struct {
	UserID int64         `json:"userId"`
	Emoji  string        `json:"emoji"`
	DocID  sql.NullInt64 `json:"docId"`
}

func (q *Queries) GetReactionOnDoc(ctx context.Context, arg GetReactionOnDocParams) (Reaction, error) {
	row := q.db.QueryRowContext(ctx, getReactionOnDoc, arg.UserID, arg.Emoji, arg.DocID)
	var i Reaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Emoji,
		&i.IssueID,
		&i.DocID,
		&i.ReleaseID,
		&i.IssueCommentID,
		&i.DocCommentID,
		&i.ReleaseCommentID,
		&i.CreatedAt,
	)
	return i, err
}

const getReactionOnDocComment = `-- name: GetReactionOnDocComment :one
SELECT id, user_id, emoji, issue_id, doc_id, release_id, issue_comment_id, doc_comment_id, release_comment_id, created_at FROM reactions
WHERE user_id = ? AND emoji = ? AND doc_comment_id = ?
LIMIT 1
`

type GetReactionOnDocCommentParams struct {
	UserID       int64         `json:"userId"`
	Emoji        string        `json:"emoji"`
	DocCommentID sql.NullInt64 `json:"docCommentId"`
}

func (q *Queries) GetReactionOnDocComment(ctx context.Context, arg GetReactionOnDocCommentParams) (Reaction, error) {
	row := q.db.QueryRowContext(ctx, getReactionOnDocComment, arg.UserID, arg.Emoji, arg.DocCommentID)
	var i Reaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Emoji,
		&i.IssueID,
		&i.DocID,
		&i.ReleaseID,
		&i.IssueCommentID,
		&i.DocCommentID,
		&i.ReleaseCommentID,
		&i.CreatedAt,
	)
	return i, err
}

const getReactionOnIssue = `-- name: GetReactionOnIssue :one
SELECT id, user_id, emoji, issue_id, doc_id, release_id, issue_comment_id, doc_comment_id, release_comment_id, created_at FROM reactions
WHERE user_id = ? AND emoji = ? AND issue_id = ?
LIMIT 1
`

type GetReactionOnIssueParams struct {
	UserID  int64         `json:"userId"`
	Emoji   string        `json:"emoji"`
	IssueID sql.NullInt64 `json:"issueId"`
}

func (q *Queries) GetReactionOnIssue(ctx context.Context, arg GetReactionOnIssueParams) (Reaction, error) {
	row := q.db.QueryRowContext(ctx, getReactionOnIssue, arg.UserID, arg.Emoji, arg.IssueID)
	var i Reaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Emoji,
		&i.IssueID,
		&i.DocID,
		&i.ReleaseID,
		&i.IssueCommentID,
		&i.DocCommentID,
		&i.ReleaseCommentID,
		&i.CreatedAt,
	)
	return i, err
}

const getReactionOnIssueComment = `-- name: GetReactionOnIssueComment :one
SELECT id, user_id, emoji, issue_id, doc_id, release_id, issue_comment_id, doc_comment_id, release_comment_id, created_at FROM reactions
WHERE user_id = ? AND emoji = ? AND issue_comment_id = ?
LIMIT 1
`

type GetReactionOnIssueCommentParams struct {
	UserID         int64         `json:"userId"`
	Emoji          string        `json:"emoji"`
	IssueCommentID sql.NullInt64 `json:"issueCommentId"`
}

func (q *Queries) GetReactionOnIssueComment(ctx context.Context, arg GetReactionOnIssueCommentParams) (Reaction, error) {
	row := q.db.QueryRowContext(ctx, getReactionOnIssueComment, arg.UserID, arg.Emoji, arg.IssueCommentID)
	var i Reaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Emoji,
		&i.IssueID,
		&i.DocID,
		&i.ReleaseID,
		&i.IssueCommentID,
		&i.DocCommentID,
		&i.ReleaseCommentID,
		&i.CreatedAt,
	)
	return i, err
}

const getReactionOnRelease = `-- name: GetReactionOnRelease :one
SELECT id, user_id, emoji, issue_id, doc_id, release_id, issue_comment_id, doc_comment_id, release_comment_id, created_at FROM reactions
WHERE user_id = ? AND emoji = ? AND release_id = ?
LIMIT 1
`

type GetReactionOnReleaseParams struct {
	UserID    int64         `json:"userId"`
	Emoji     string        `json:"emoji"`
	ReleaseID sql.NullInt64 `json:"releaseId"`
}

func (q *Queries) GetReactionOnRelease(ctx context.Context, arg GetReactionOnReleaseParams) (Reaction, error) {
	row := q.db.QueryRowContext(ctx, getReactionOnRelease, arg.UserID, arg.Emoji, arg.ReleaseID)
	var i Reaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Emoji,
		&i.IssueID,
		&i.DocID,
		&i.ReleaseID,
		&i.IssueCommentID,
		&i.DocCommentID,
		&i.ReleaseCommentID,
		&i.CreatedAt,
	)
	return i, err
}

const getReactionOnReleaseComment = `-- name: GetReactionOnReleaseComment :one
SELECT id, user_id, emoji, issue_id, doc_id, release_id, issue_comment_id, doc_comment_id, release_comment_id, created_at FROM reactions
WHERE user_id = ? AND emoji = ? AND release_comment_id = ?
LIMIT 1
`

type GetReactionOnReleaseCommentParams struct {
	UserID           int64         `json:"userId"`
	Emoji            string        `json:"emoji"`
	ReleaseCommentID sql.NullInt64 `json:"releaseCommentId"`
}

func (q *Queries) GetReactionOnReleaseComment(ctx context.Context, arg GetReactionOnReleaseCommentParams) (Reaction, error) {
	row := q.db.QueryRowContext(ctx, getReactionOnReleaseComment, arg.UserID, arg.Emoji, arg.ReleaseCommentID)
	var i Reaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Emoji,
		&i.IssueID,
		&i.DocID,
		&i.ReleaseID,
		&i.IssueCommentID,
		&i.DocCommentID,
		&i.ReleaseCommentID,
		&i.CreatedAt,
	)
	return i, err
}

const listReactionsByDoc = `-- name: ListReactionsByDoc :many

SELECT r.id, r.user_id, r.emoji, r.issue_id, r.doc_id, r.release_id, r.issue_comment_id, r.doc_comment_id, r.release_comment_id, r.created_at, u.username, u.full_name, u.avatar_url
FROM reactions r
JOIN users u ON r.user_id = u.id
WHERE r.doc_id = ?
ORDER BY r.created_at ASC
`

type ListReactionsByDocRow struct {
	ID               int64          `json:"id"`
	UserID           int64          `json:"userId"`
	Emoji            string         `json:"emoji"`
	IssueID          sql.NullInt64  `json:"issueId"`
	DocID            sql.NullInt64  `json:"docId"`
	ReleaseID        sql.NullInt64  `json:"releaseId"`
	IssueCommentID   sql.NullInt64  `json:"issueCommentId"`
	DocCommentID     sql.NullInt64  `json:"docCommentId"`
	ReleaseCommentID sql.NullInt64  `json:"releaseCommentId"`
	CreatedAt        time.Time      `json:"createdAt"`
	Username         string         `json:"username"`
	FullName         string         `json:"fullName"`
	AvatarUrl        sql.NullString `json:"avatarUrl"`
}

// ============================================
// Doc Reactions
// ============================================
func (q *Queries) ListReactionsByDoc(ctx context.Context, docID sql.NullInt64) ([]ListReactionsByDocRow, error) {
	rows, err := q.db.QueryContext(ctx, listReactionsByDoc, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReactionsByDocRow{}
	for rows.Next() {
		var i ListReactionsByDocRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Emoji,
			&i.IssueID,
			&i.DocID,
			&i.ReleaseID,
			&i.IssueCommentID,
			&i.DocCommentID,
			&i.ReleaseCommentID,
			&i.CreatedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactionsByDocComment = `-- name: ListReactionsByDocComment :many

SELECT r.id, r.user_id, r.emoji, r.issue_id, r.doc_id, r.release_id, r.issue_comment_id, r.doc_comment_id, r.release_comment_id, r.created_at, u.username, u.full_name, u.avatar_url
FROM reactions r
JOIN users u ON r.user_id = u.id
WHERE r.doc_comment_id = ?
ORDER BY r.created_at ASC
`

type ListReactionsByDocCommentRow struct {
	ID               int64          `json:"id"`
	UserID           int64          `json:"userId"`
	Emoji            string         `json:"emoji"`
	IssueID          sql.NullInt64  `json:"issueId"`
	DocID            sql.NullInt64  `json:"docId"`
	ReleaseID        sql.NullInt64  `json:"releaseId"`
	IssueCommentID   sql.NullInt64  `json:"issueCommentId"`
	DocCommentID     sql.NullInt64  `json:"docCommentId"`
	ReleaseCommentID sql.NullInt64  `json:"releaseCommentId"`
	CreatedAt        time.Time      `json:"createdAt"`
	Username         string         `json:"username"`
	FullName         string         `json:"fullName"`
	AvatarUrl        sql.NullString `json:"avatarUrl"`
}

// ============================================
// Doc Comment Reactions
// ============================================
func (q *Queries) ListReactionsByDocComment(ctx context.Context, docCommentID sql.NullInt64) ([]ListReactionsByDocCommentRow, error) {
	rows, err := q.db.QueryContext(ctx, listReactionsByDocComment, docCommentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReactionsByDocCommentRow{}
	for rows.Next() {
		var i ListReactionsByDocCommentRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Emoji,
			&i.IssueID,
			&i.DocID,
			&i.ReleaseID,
			&i.IssueCommentID,
			&i.DocCommentID,
			&i.ReleaseCommentID,
			&i.CreatedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactionsByIssue = `-- name: ListReactionsByIssue :many


SELECT r.id, r.user_id, r.emoji, r.issue_id, r.doc_id, r.release_id, r.issue_comment_id, r.doc_comment_id, r.release_comment_id, r.created_at, u.username, u.full_name, u.avatar_url
FROM reactions r
JOIN users u ON r.user_id = u.id
WHERE r.issue_id = ?
ORDER BY r.created_at ASC
`

type ListReactionsByIssueRow struct {
	ID               int64          `json:"id"`
	UserID           int64          `json:"userId"`
	Emoji            string         `json:"emoji"`
	IssueID          sql.NullInt64  `json:"issueId"`
	DocID            sql.NullInt64  `json:"docId"`
	ReleaseID        sql.NullInt64  `json:"releaseId"`
	IssueCommentID   sql.NullInt64  `json:"issueCommentId"`
	DocCommentID     sql.NullInt64  `json:"docCommentId"`
	ReleaseCommentID sql.NullInt64  `json:"releaseCommentId"`
	CreatedAt        time.Time      `json:"createdAt"`
	Username         string         `json:"username"`
	FullName         string         `json:"fullName"`
	AvatarUrl        sql.NullString `json:"avatarUrl"`
}

// ============================================
// Reactions Queries
// ============================================
// ============================================
// Issue Reactions
// ============================================
func (q *Queries) ListReactionsByIssue(ctx context.Context, issueID sql.NullInt64) ([]ListReactionsByIssueRow, error) {
	rows, err := q.db.QueryContext(ctx, listReactionsByIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReactionsByIssueRow{}
	for rows.Next() {
		var i ListReactionsByIssueRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Emoji,
			&i.IssueID,
			&i.DocID,
			&i.ReleaseID,
			&i.IssueCommentID,
			&i.DocCommentID,
			&i.ReleaseCommentID,
			&i.CreatedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactionsByIssueComment = `-- name: ListReactionsByIssueComment :many

SELECT r.id, r.user_id, r.emoji, r.issue_id, r.doc_id, r.release_id, r.issue_comment_id, r.doc_comment_id, r.release_comment_id, r.created_at, u.username, u.full_name, u.avatar_url
FROM reactions r
JOIN users u ON r.user_id = u.id
WHERE r.issue_comment_id = ?
ORDER BY r.created_at ASC
`

type ListReactionsByIssueCommentRow struct {
	ID               int64          `json:"id"`
	UserID           int64          `json:"userId"`
	Emoji            string         `json:"emoji"`
	IssueID          sql.NullInt64  `json:"issueId"`
	DocID            sql.NullInt64  `json:"docId"`
	ReleaseID        sql.NullInt64  `json:"releaseId"`
	IssueCommentID   sql.NullInt64  `json:"issueCommentId"`
	DocCommentID     sql.NullInt64  `json:"docCommentId"`
	ReleaseCommentID sql.NullInt64  `json:"releaseCommentId"`
	CreatedAt        time.Time      `json:"createdAt"`
	Username         string         `json:"username"`
	FullName         string         `json:"fullName"`
	AvatarUrl        sql.NullString `json:"avatarUrl"`
}

// ============================================
// Issue Comment Reactions
// ============================================
func (q *Queries) ListReactionsByIssueComment(ctx context.Context, issueCommentID sql.NullInt64) ([]ListReactionsByIssueCommentRow, error) {
	rows, err := q.db.QueryContext(ctx, listReactionsByIssueComment, issueCommentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReactionsByIssueCommentRow{}
	for rows.Next() {
		var i ListReactionsByIssueCommentRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Emoji,
			&i.IssueID,
			&i.DocID,
			&i.ReleaseID,
			&i.IssueCommentID,
			&i.DocCommentID,
			&i.ReleaseCommentID,
			&i.CreatedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactionsByRelease = `-- name: ListReactionsByRelease :many

SELECT r.id, r.user_id, r.emoji, r.issue_id, r.doc_id, r.release_id, r.issue_comment_id, r.doc_comment_id, r.release_comment_id, r.created_at, u.username, u.full_name, u.avatar_url
FROM reactions r
JOIN users u ON r.user_id = u.id
WHERE r.release_id = ?
ORDER BY r.created_at ASC
`

type ListReactionsByReleaseRow struct {
	ID               int64          `json:"id"`
	UserID           int64          `json:"userId"`
	Emoji            string         `json:"emoji"`
	IssueID          sql.NullInt64  `json:"issueId"`
	DocID            sql.NullInt64  `json:"docId"`
	ReleaseID        sql.NullInt64  `json:"releaseId"`
	IssueCommentID   sql.NullInt64  `json:"issueCommentId"`
	DocCommentID     sql.NullInt64  `json:"docCommentId"`
	ReleaseCommentID sql.NullInt64  `json:"releaseCommentId"`
	CreatedAt        time.Time      `json:"createdAt"`
	Username         string         `json:"username"`
	FullName         string         `json:"fullName"`
	AvatarUrl        sql.NullString `json:"avatarUrl"`
}

// ============================================
// Release Reactions
// ============================================
func (q *Queries) ListReactionsByRelease(ctx context.Context, releaseID sql.NullInt64) ([]ListReactionsByReleaseRow, error) {
	rows, err := q.db.QueryContext(ctx, listReactionsByRelease, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReactionsByReleaseRow{}
	for rows.Next() {
		var i ListReactionsByReleaseRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Emoji,
			&i.IssueID,
			&i.DocID,
			&i.ReleaseID,
			&i.IssueCommentID,
			&i.DocCommentID,
			&i.ReleaseCommentID,
			&i.CreatedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactionsByReleaseComment = `-- name: ListReactionsByReleaseComment :many

SELECT r.id, r.user_id, r.emoji, r.issue_id, r.doc_id, r.release_id, r.issue_comment_id, r.doc_comment_id, r.release_comment_id, r.created_at, u.username, u.full_name, u.avatar_url
FROM reactions r
JOIN users u ON r.user_id = u.id
WHERE r.release_comment_id = ?
ORDER BY r.created_at ASC
`

type ListReactionsByReleaseCommentRow struct {
	ID               int64          `json:"id"`
	UserID           int64          `json:"userId"`
	Emoji            string         `json:"emoji"`
	IssueID          sql.NullInt64  `json:"issueId"`
	DocID            sql.NullInt64  `json:"docId"`
	ReleaseID        sql.NullInt64  `json:"releaseId"`
	IssueCommentID   sql.NullInt64  `json:"issueCommentId"`
	DocCommentID     sql.NullInt64  `json:"docCommentId"`
	ReleaseCommentID sql.NullInt64  `json:"releaseCommentId"`
	CreatedAt        time.Time      `json:"createdAt"`
	Username         string         `json:"username"`
	FullName         string         `json:"fullName"`
	AvatarUrl        sql.NullString `json:"avatarUrl"`
}

// ============================================
// Release Comment Reactions
// ============================================
func (q *Queries) ListReactionsByReleaseComment(ctx context.Context, releaseCommentID sql.NullInt64) ([]ListReactionsByReleaseCommentRow, error) {
	rows, err := q.db.QueryContext(ctx, listReactionsByReleaseComment, releaseCommentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReactionsByReleaseCommentRow{}
	for rows.Next() {
		var i ListReactionsByReleaseCommentRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Emoji,
			&i.IssueID,
			&i.DocID,
			&i.ReleaseID,
			&i.IssueCommentID,
			&i.DocCommentID,
			&i.ReleaseCommentID,
			&i.CreatedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
