// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: releases.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countReleases = `-- name: CountReleases :one
SELECT COUNT(*) FROM releases WHERE is_draft = 0
`

func (q *Queries) CountReleases(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReleases)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReleasesByProject = `-- name: CountReleasesByProject :one
SELECT COUNT(*) FROM releases WHERE project_id = ? AND is_draft = 0
`

func (q *Queries) CountReleasesByProject(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReleasesByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRelease = `-- name: CreateRelease :one
INSERT INTO releases (project_id, version, title, description, author_id, is_draft, is_prerelease)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, version, title, description, author_id, is_draft, is_prerelease, published_at, created_at, updated_at
`

type CreateReleaseParams struct {
	ProjectID    int64          `json:"projectId"`
	Version      string         `json:"version"`
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	AuthorID     int64          `json:"authorId"`
	IsDraft      bool           `json:"isDraft"`
	IsPrerelease bool           `json:"isPrerelease"`
}

func (q *Queries) CreateRelease(ctx context.Context, arg CreateReleaseParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, createRelease,
		arg.ProjectID,
		arg.Version,
		arg.Title,
		arg.Description,
		arg.AuthorID,
		arg.IsDraft,
		arg.IsPrerelease,
	)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.IsDraft,
		&i.IsPrerelease,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReleaseFile = `-- name: CreateReleaseFile :one
INSERT INTO release_files (release_id, filename, original_filename, file_path, file_size, mime_type, sha256_hash)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, release_id, filename, original_filename, file_path, file_size, mime_type, sha256_hash, download_count, created_at
`

type CreateReleaseFileParams struct {
	ReleaseID        int64          `json:"releaseId"`
	Filename         string         `json:"filename"`
	OriginalFilename string         `json:"originalFilename"`
	FilePath         string         `json:"filePath"`
	FileSize         int64          `json:"fileSize"`
	MimeType         string         `json:"mimeType"`
	Sha256Hash       sql.NullString `json:"sha256Hash"`
}

func (q *Queries) CreateReleaseFile(ctx context.Context, arg CreateReleaseFileParams) (ReleaseFile, error) {
	row := q.db.QueryRowContext(ctx, createReleaseFile,
		arg.ReleaseID,
		arg.Filename,
		arg.OriginalFilename,
		arg.FilePath,
		arg.FileSize,
		arg.MimeType,
		arg.Sha256Hash,
	)
	var i ReleaseFile
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.Filename,
		&i.OriginalFilename,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.Sha256Hash,
		&i.DownloadCount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRelease = `-- name: DeleteRelease :exec
DELETE FROM releases WHERE id = ?
`

func (q *Queries) DeleteRelease(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRelease, id)
	return err
}

const deleteReleaseFile = `-- name: DeleteReleaseFile :exec
DELETE FROM release_files WHERE id = ?
`

func (q *Queries) DeleteReleaseFile(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReleaseFile, id)
	return err
}

const deleteReleaseFiles = `-- name: DeleteReleaseFiles :exec
DELETE FROM release_files WHERE release_id = ?
`

func (q *Queries) DeleteReleaseFiles(ctx context.Context, releaseID int64) error {
	_, err := q.db.ExecContext(ctx, deleteReleaseFiles, releaseID)
	return err
}

const getLatestRelease = `-- name: GetLatestRelease :one
SELECT 
    r.id, r.project_id, r.version, r.title, r.description, r.author_id, r.is_draft, r.is_prerelease, r.published_at, r.created_at, r.updated_at,
    p.key as project_key,
    a.username as author_username
FROM releases r
LEFT JOIN projects p ON r.project_id = p.id
JOIN users a ON r.author_id = a.id
WHERE r.project_id = ? AND r.is_draft = 0
ORDER BY r.published_at DESC
LIMIT 1
`

type GetLatestReleaseRow struct {
	ID             int64          `json:"id"`
	ProjectID      int64          `json:"projectId"`
	Version        string         `json:"version"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	AuthorID       int64          `json:"authorId"`
	IsDraft        bool           `json:"isDraft"`
	IsPrerelease   bool           `json:"isPrerelease"`
	PublishedAt    sql.NullTime   `json:"publishedAt"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	ProjectKey     string         `json:"projectKey"`
	AuthorUsername string         `json:"authorUsername"`
}

func (q *Queries) GetLatestRelease(ctx context.Context, projectID int64) (GetLatestReleaseRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestRelease, projectID)
	var i GetLatestReleaseRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.IsDraft,
		&i.IsPrerelease,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectKey,
		&i.AuthorUsername,
	)
	return i, err
}

const getReleaseByID = `-- name: GetReleaseByID :one

SELECT 
    r.id, r.project_id, r.version, r.title, r.description, r.author_id, r.is_draft, r.is_prerelease, r.published_at, r.created_at, r.updated_at,
    p.key as project_key,
    p.name as project_name,
    a.username as author_username,
    a.full_name as author_full_name
FROM releases r
LEFT JOIN projects p ON r.project_id = p.id
JOIN users a ON r.author_id = a.id
WHERE r.id = ? LIMIT 1
`

type GetReleaseByIDRow struct {
	ID             int64          `json:"id"`
	ProjectID      int64          `json:"projectId"`
	Version        string         `json:"version"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	AuthorID       int64          `json:"authorId"`
	IsDraft        bool           `json:"isDraft"`
	IsPrerelease   bool           `json:"isPrerelease"`
	PublishedAt    sql.NullTime   `json:"publishedAt"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	ProjectKey     string         `json:"projectKey"`
	ProjectName    string         `json:"projectName"`
	AuthorUsername string         `json:"authorUsername"`
	AuthorFullName string         `json:"authorFullName"`
}

// ============================================
// Release Queries (The Granary)
// ============================================
func (q *Queries) GetReleaseByID(ctx context.Context, id int64) (GetReleaseByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getReleaseByID, id)
	var i GetReleaseByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.IsDraft,
		&i.IsPrerelease,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectKey,
		&i.ProjectName,
		&i.AuthorUsername,
		&i.AuthorFullName,
	)
	return i, err
}

const getReleaseByVersion = `-- name: GetReleaseByVersion :one
SELECT 
    r.id, r.project_id, r.version, r.title, r.description, r.author_id, r.is_draft, r.is_prerelease, r.published_at, r.created_at, r.updated_at,
    p.key as project_key,
    p.name as project_name,
    a.username as author_username,
    a.full_name as author_full_name
FROM releases r
LEFT JOIN projects p ON r.project_id = p.id
JOIN users a ON r.author_id = a.id
WHERE r.project_id = ? AND r.version = ?
LIMIT 1
`

type GetReleaseByVersionParams struct {
	ProjectID int64  `json:"projectId"`
	Version   string `json:"version"`
}

type GetReleaseByVersionRow struct {
	ID             int64          `json:"id"`
	ProjectID      int64          `json:"projectId"`
	Version        string         `json:"version"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	AuthorID       int64          `json:"authorId"`
	IsDraft        bool           `json:"isDraft"`
	IsPrerelease   bool           `json:"isPrerelease"`
	PublishedAt    sql.NullTime   `json:"publishedAt"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	ProjectKey     string         `json:"projectKey"`
	ProjectName    string         `json:"projectName"`
	AuthorUsername string         `json:"authorUsername"`
	AuthorFullName string         `json:"authorFullName"`
}

func (q *Queries) GetReleaseByVersion(ctx context.Context, arg GetReleaseByVersionParams) (GetReleaseByVersionRow, error) {
	row := q.db.QueryRowContext(ctx, getReleaseByVersion, arg.ProjectID, arg.Version)
	var i GetReleaseByVersionRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.IsDraft,
		&i.IsPrerelease,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectKey,
		&i.ProjectName,
		&i.AuthorUsername,
		&i.AuthorFullName,
	)
	return i, err
}

const getReleaseFileByID = `-- name: GetReleaseFileByID :one

SELECT id, release_id, filename, original_filename, file_path, file_size, mime_type, sha256_hash, download_count, created_at FROM release_files WHERE id = ? LIMIT 1
`

// ============================================
// Release File Queries
// ============================================
func (q *Queries) GetReleaseFileByID(ctx context.Context, id int64) (ReleaseFile, error) {
	row := q.db.QueryRowContext(ctx, getReleaseFileByID, id)
	var i ReleaseFile
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.Filename,
		&i.OriginalFilename,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.Sha256Hash,
		&i.DownloadCount,
		&i.CreatedAt,
	)
	return i, err
}

const getReleaseFileByName = `-- name: GetReleaseFileByName :one
SELECT id, release_id, filename, original_filename, file_path, file_size, mime_type, sha256_hash, download_count, created_at FROM release_files WHERE release_id = ? AND filename = ? LIMIT 1
`

type GetReleaseFileByNameParams struct {
	ReleaseID int64  `json:"releaseId"`
	Filename  string `json:"filename"`
}

func (q *Queries) GetReleaseFileByName(ctx context.Context, arg GetReleaseFileByNameParams) (ReleaseFile, error) {
	row := q.db.QueryRowContext(ctx, getReleaseFileByName, arg.ReleaseID, arg.Filename)
	var i ReleaseFile
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.Filename,
		&i.OriginalFilename,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.Sha256Hash,
		&i.DownloadCount,
		&i.CreatedAt,
	)
	return i, err
}

const getTotalDownloads = `-- name: GetTotalDownloads :one
SELECT COALESCE(SUM(download_count), 0) FROM release_files WHERE release_id = ?
`

func (q *Queries) GetTotalDownloads(ctx context.Context, releaseID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalDownloads, releaseID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const listAllReleases = `-- name: ListAllReleases :many
SELECT 
    r.id, r.project_id, r.version, r.title, r.description, r.author_id, r.is_draft, r.is_prerelease, r.published_at, r.created_at, r.updated_at,
    p.key as project_key,
    a.username as author_username
FROM releases r
LEFT JOIN projects p ON r.project_id = p.id
JOIN users a ON r.author_id = a.id
ORDER BY r.is_draft DESC, r.created_at DESC
`

type ListAllReleasesRow struct {
	ID             int64          `json:"id"`
	ProjectID      int64          `json:"projectId"`
	Version        string         `json:"version"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	AuthorID       int64          `json:"authorId"`
	IsDraft        bool           `json:"isDraft"`
	IsPrerelease   bool           `json:"isPrerelease"`
	PublishedAt    sql.NullTime   `json:"publishedAt"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	ProjectKey     string         `json:"projectKey"`
	AuthorUsername string         `json:"authorUsername"`
}

// Include drafts (for admin/author)
func (q *Queries) ListAllReleases(ctx context.Context) ([]ListAllReleasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllReleases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllReleasesRow{}
	for rows.Next() {
		var i ListAllReleasesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Version,
			&i.Title,
			&i.Description,
			&i.AuthorID,
			&i.IsDraft,
			&i.IsPrerelease,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectKey,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftReleases = `-- name: ListDraftReleases :many
SELECT 
    r.id, r.project_id, r.version, r.title, r.description, r.author_id, r.is_draft, r.is_prerelease, r.published_at, r.created_at, r.updated_at,
    p.key as project_key,
    a.username as author_username
FROM releases r
LEFT JOIN projects p ON r.project_id = p.id
JOIN users a ON r.author_id = a.id
WHERE r.is_draft = 1
ORDER BY r.created_at DESC
`

type ListDraftReleasesRow struct {
	ID             int64          `json:"id"`
	ProjectID      int64          `json:"projectId"`
	Version        string         `json:"version"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	AuthorID       int64          `json:"authorId"`
	IsDraft        bool           `json:"isDraft"`
	IsPrerelease   bool           `json:"isPrerelease"`
	PublishedAt    sql.NullTime   `json:"publishedAt"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	ProjectKey     string         `json:"projectKey"`
	AuthorUsername string         `json:"authorUsername"`
}

func (q *Queries) ListDraftReleases(ctx context.Context) ([]ListDraftReleasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDraftReleases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDraftReleasesRow{}
	for rows.Next() {
		var i ListDraftReleasesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Version,
			&i.Title,
			&i.Description,
			&i.AuthorID,
			&i.IsDraft,
			&i.IsPrerelease,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectKey,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleaseFiles = `-- name: ListReleaseFiles :many
SELECT id, release_id, filename, original_filename, file_path, file_size, mime_type, sha256_hash, download_count, created_at FROM release_files WHERE release_id = ? ORDER BY filename
`

func (q *Queries) ListReleaseFiles(ctx context.Context, releaseID int64) ([]ReleaseFile, error) {
	rows, err := q.db.QueryContext(ctx, listReleaseFiles, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReleaseFile{}
	for rows.Next() {
		var i ReleaseFile
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.Filename,
			&i.OriginalFilename,
			&i.FilePath,
			&i.FileSize,
			&i.MimeType,
			&i.Sha256Hash,
			&i.DownloadCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleases = `-- name: ListReleases :many
SELECT 
    r.id, r.project_id, r.version, r.title, r.description, r.author_id, r.is_draft, r.is_prerelease, r.published_at, r.created_at, r.updated_at,
    p.key as project_key,
    p.name as project_name,
    a.username as author_username
FROM releases r
LEFT JOIN projects p ON r.project_id = p.id
JOIN users a ON r.author_id = a.id
WHERE r.is_draft = 0
ORDER BY r.published_at DESC
`

type ListReleasesRow struct {
	ID             int64          `json:"id"`
	ProjectID      int64          `json:"projectId"`
	Version        string         `json:"version"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	AuthorID       int64          `json:"authorId"`
	IsDraft        bool           `json:"isDraft"`
	IsPrerelease   bool           `json:"isPrerelease"`
	PublishedAt    sql.NullTime   `json:"publishedAt"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	ProjectKey     string         `json:"projectKey"`
	ProjectName    string         `json:"projectName"`
	AuthorUsername string         `json:"authorUsername"`
}

func (q *Queries) ListReleases(ctx context.Context) ([]ListReleasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listReleases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReleasesRow{}
	for rows.Next() {
		var i ListReleasesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Version,
			&i.Title,
			&i.Description,
			&i.AuthorID,
			&i.IsDraft,
			&i.IsPrerelease,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectKey,
			&i.ProjectName,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleasesByProject = `-- name: ListReleasesByProject :many
SELECT 
    r.id, r.project_id, r.version, r.title, r.description, r.author_id, r.is_draft, r.is_prerelease, r.published_at, r.created_at, r.updated_at,
    a.username as author_username
FROM releases r
JOIN users a ON r.author_id = a.id
WHERE r.project_id = ? AND r.is_draft = 0
ORDER BY r.published_at DESC
`

type ListReleasesByProjectRow struct {
	ID             int64          `json:"id"`
	ProjectID      int64          `json:"projectId"`
	Version        string         `json:"version"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	AuthorID       int64          `json:"authorId"`
	IsDraft        bool           `json:"isDraft"`
	IsPrerelease   bool           `json:"isPrerelease"`
	PublishedAt    sql.NullTime   `json:"publishedAt"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	AuthorUsername string         `json:"authorUsername"`
}

func (q *Queries) ListReleasesByProject(ctx context.Context, projectID int64) ([]ListReleasesByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listReleasesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReleasesByProjectRow{}
	for rows.Next() {
		var i ListReleasesByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Version,
			&i.Title,
			&i.Description,
			&i.AuthorID,
			&i.IsDraft,
			&i.IsPrerelease,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishRelease = `-- name: PublishRelease :one
UPDATE releases SET
    is_draft = 0,
    published_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, project_id, version, title, description, author_id, is_draft, is_prerelease, published_at, created_at, updated_at
`

func (q *Queries) PublishRelease(ctx context.Context, id int64) (Release, error) {
	row := q.db.QueryRowContext(ctx, publishRelease, id)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.IsDraft,
		&i.IsPrerelease,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unpublishRelease = `-- name: UnpublishRelease :exec
UPDATE releases SET
    is_draft = 1,
    published_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UnpublishRelease(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, unpublishRelease, id)
	return err
}

const updateRelease = `-- name: UpdateRelease :one
UPDATE releases SET
    version = COALESCE(?, version),
    title = COALESCE(?, title),
    description = COALESCE(?, description),
    is_prerelease = COALESCE(?, is_prerelease),
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, project_id, version, title, description, author_id, is_draft, is_prerelease, published_at, created_at, updated_at
`

type UpdateReleaseParams struct {
	Version      string         `json:"version"`
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	IsPrerelease bool           `json:"isPrerelease"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateRelease(ctx context.Context, arg UpdateReleaseParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, updateRelease,
		arg.Version,
		arg.Title,
		arg.Description,
		arg.IsPrerelease,
		arg.ID,
	)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.IsDraft,
		&i.IsPrerelease,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReleaseFileDownloadCount = `-- name: UpdateReleaseFileDownloadCount :exec
UPDATE release_files SET download_count = download_count + 1 WHERE id = ?
`

func (q *Queries) UpdateReleaseFileDownloadCount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateReleaseFileDownloadCount, id)
	return err
}
