// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: release_comments.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countCommentsByRelease = `-- name: CountCommentsByRelease :one
SELECT COUNT(*) FROM release_comments WHERE release_id = ?
`

func (q *Queries) CountCommentsByRelease(ctx context.Context, releaseID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCommentsByRelease, releaseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReleaseComment = `-- name: CreateReleaseComment :one
INSERT INTO release_comments (release_id, author_id, content)
VALUES (?, ?, ?)
RETURNING id, release_id, author_id, content, created_at, updated_at
`

type CreateReleaseCommentParams struct {
	ReleaseID int64  `json:"releaseId"`
	AuthorID  int64  `json:"authorId"`
	Content   string `json:"content"`
}

func (q *Queries) CreateReleaseComment(ctx context.Context, arg CreateReleaseCommentParams) (ReleaseComment, error) {
	row := q.db.QueryRowContext(ctx, createReleaseComment, arg.ReleaseID, arg.AuthorID, arg.Content)
	var i ReleaseComment
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReleaseComment = `-- name: DeleteReleaseComment :exec
DELETE FROM release_comments WHERE id = ?
`

func (q *Queries) DeleteReleaseComment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReleaseComment, id)
	return err
}

const deleteReleaseCommentByAuthor = `-- name: DeleteReleaseCommentByAuthor :execrows
DELETE FROM release_comments WHERE id = ? AND author_id = ?
`

type DeleteReleaseCommentByAuthorParams struct {
	ID       int64 `json:"id"`
	AuthorID int64 `json:"authorId"`
}

// Only allow author to delete their own comment
func (q *Queries) DeleteReleaseCommentByAuthor(ctx context.Context, arg DeleteReleaseCommentByAuthorParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteReleaseCommentByAuthor, arg.ID, arg.AuthorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getReleaseCommentByID = `-- name: GetReleaseCommentByID :one

SELECT c.id, c.release_id, c.author_id, c.content, c.created_at, c.updated_at, u.username as author_username, u.full_name as author_full_name, u.avatar_url as author_avatar
FROM release_comments c
JOIN users u ON c.author_id = u.id
WHERE c.id = ? LIMIT 1
`

type GetReleaseCommentByIDRow struct {
	ID             int64          `json:"id"`
	ReleaseID      int64          `json:"releaseId"`
	AuthorID       int64          `json:"authorId"`
	Content        string         `json:"content"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	AuthorUsername string         `json:"authorUsername"`
	AuthorFullName string         `json:"authorFullName"`
	AuthorAvatar   sql.NullString `json:"authorAvatar"`
}

// ============================================
// Release Comment Queries
// ============================================
func (q *Queries) GetReleaseCommentByID(ctx context.Context, id int64) (GetReleaseCommentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getReleaseCommentByID, id)
	var i GetReleaseCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorUsername,
		&i.AuthorFullName,
		&i.AuthorAvatar,
	)
	return i, err
}

const listCommentsByRelease = `-- name: ListCommentsByRelease :many
SELECT c.id, c.release_id, c.author_id, c.content, c.created_at, c.updated_at, u.username as author_username, u.full_name as author_full_name, u.avatar_url as author_avatar
FROM release_comments c
JOIN users u ON c.author_id = u.id
WHERE c.release_id = ?
ORDER BY c.created_at ASC
`

type ListCommentsByReleaseRow struct {
	ID             int64          `json:"id"`
	ReleaseID      int64          `json:"releaseId"`
	AuthorID       int64          `json:"authorId"`
	Content        string         `json:"content"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	AuthorUsername string         `json:"authorUsername"`
	AuthorFullName string         `json:"authorFullName"`
	AuthorAvatar   sql.NullString `json:"authorAvatar"`
}

func (q *Queries) ListCommentsByRelease(ctx context.Context, releaseID int64) ([]ListCommentsByReleaseRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByRelease, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsByReleaseRow{}
	for rows.Next() {
		var i ListCommentsByReleaseRow
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.AuthorFullName,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
