// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countUserSessions = `-- name: CountUserSessions :one
SELECT COUNT(*) FROM sessions 
WHERE user_id = ? AND expires_at > datetime('now')
`

func (q *Queries) CountUserSessions(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserSessions, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token, user_agent, ip_address, expires_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, token, user_agent, ip_address, expires_at, created_at
`

type CreateSessionParams struct {
	UserID    int64          `json:"userId"`
	Token     string         `json:"token"`
	UserAgent sql.NullString `json:"userAgent"`
	IpAddress sql.NullString `json:"ipAddress"`
	ExpiresAt time.Time      `json:"expiresAt"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.UserID,
		arg.Token,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < datetime('now')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteOldestUserSessions = `-- name: DeleteOldestUserSessions :exec
DELETE FROM sessions 
WHERE sessions.user_id = ? AND sessions.id NOT IN (
    SELECT s.id FROM sessions s
    WHERE s.user_id = ? 
    ORDER BY s.created_at DESC 
    LIMIT ?
)
`

type DeleteOldestUserSessionsParams struct {
	UserID   int64 `json:"userId"`
	UserID_2 int64 `json:"userId2"`
	Limit    int64 `json:"limit"`
}

// Keep only the N most recent sessions per user
func (q *Queries) DeleteOldestUserSessions(ctx context.Context, arg DeleteOldestUserSessionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteOldestUserSessions, arg.UserID, arg.UserID_2, arg.Limit)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one

SELECT s.id, s.user_id, s.token, s.user_agent, s.ip_address, s.expires_at, s.created_at, u.username, u.email, u.full_name
FROM sessions s
JOIN users u ON s.user_id = u.id
WHERE s.token = ? AND s.expires_at > datetime('now') AND u.is_active = 1
LIMIT 1
`

type GetSessionByTokenRow struct {
	ID        int64          `json:"id"`
	UserID    int64          `json:"userId"`
	Token     string         `json:"token"`
	UserAgent sql.NullString `json:"userAgent"`
	IpAddress sql.NullString `json:"ipAddress"`
	ExpiresAt time.Time      `json:"expiresAt"`
	CreatedAt time.Time      `json:"createdAt"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	FullName  string         `json:"fullName"`
}

// ============================================
// Session Queries
// ============================================
func (q *Queries) GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, token)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Username,
		&i.Email,
		&i.FullName,
	)
	return i, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, user_id, token, user_agent, ip_address, expires_at, created_at FROM sessions 
WHERE user_id = ? AND expires_at > datetime('now')
ORDER BY created_at DESC
`

func (q *Queries) ListUserSessions(ctx context.Context, userID int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.UserAgent,
			&i.IpAddress,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
