// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: telegram.sql

package db

import (
	"context"
	"time"
)

const createTelegramLinkToken = `-- name: CreateTelegramLinkToken :exec

INSERT INTO telegram_link_tokens (user_id, token, expires_at)
VALUES (?, ?, ?)
ON CONFLICT(user_id) DO UPDATE SET token = excluded.token, expires_at = excluded.expires_at
`

type CreateTelegramLinkTokenParams struct {
	UserID    int64     `json:"userId"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expiresAt"`
}

// ============================================
// Telegram Link Token Queries
// ============================================
func (q *Queries) CreateTelegramLinkToken(ctx context.Context, arg CreateTelegramLinkTokenParams) error {
	_, err := q.db.ExecContext(ctx, createTelegramLinkToken, arg.UserID, arg.Token, arg.ExpiresAt)
	return err
}

const deleteExpiredTelegramLinkTokens = `-- name: DeleteExpiredTelegramLinkTokens :exec
DELETE FROM telegram_link_tokens WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredTelegramLinkTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredTelegramLinkTokens)
	return err
}

const deleteTelegramLinkToken = `-- name: DeleteTelegramLinkToken :exec
DELETE FROM telegram_link_tokens WHERE user_id = ?
`

func (q *Queries) DeleteTelegramLinkToken(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTelegramLinkToken, userID)
	return err
}

const getTelegramLinkToken = `-- name: GetTelegramLinkToken :one
SELECT id, user_id, token, expires_at, created_at FROM telegram_link_tokens WHERE token = ? LIMIT 1
`

func (q *Queries) GetTelegramLinkToken(ctx context.Context, token string) (TelegramLinkToken, error) {
	row := q.db.QueryRowContext(ctx, getTelegramLinkToken, token)
	var i TelegramLinkToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
