// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const activateUser = `-- name: ActivateUser :exec
UPDATE users SET is_active = 1, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) ActivateUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, activateUser, id)
	return err
}

const clearUserTelegramChatID = `-- name: ClearUserTelegramChatID :exec
UPDATE users 
SET telegram_chat_id = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) ClearUserTelegramChatID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearUserTelegramChatID, id)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users WHERE is_active = 1
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, full_name, avatar_url, is_active)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, username, email, password_hash, full_name, avatar_url, is_active, created_at, updated_at, telegram_chat_id, language
`

type CreateUserParams struct {
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"passwordHash"`
	FullName     string         `json:"fullName"`
	AvatarUrl    sql.NullString `json:"avatarUrl"`
	IsActive     bool           `json:"isActive"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.AvatarUrl,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramChatID,
		&i.Language,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users SET is_active = 0, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) DeactivateUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deactivateUser, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, full_name, avatar_url, is_active, created_at, updated_at, telegram_chat_id, language FROM users WHERE email = ? COLLATE NOCASE LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramChatID,
		&i.Language,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, username, email, password_hash, full_name, avatar_url, is_active, created_at, updated_at, telegram_chat_id, language FROM users WHERE id = ? LIMIT 1
`

// ============================================
// User Queries
// ============================================
func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramChatID,
		&i.Language,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, full_name, avatar_url, is_active, created_at, updated_at, telegram_chat_id, language FROM users WHERE username = ? COLLATE NOCASE LIMIT 1
`

// Smart login: find user by username (case-insensitive)
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramChatID,
		&i.Language,
	)
	return i, err
}

const getUserByUsernameOrEmail = `-- name: GetUserByUsernameOrEmail :one
SELECT id, username, email, password_hash, full_name, avatar_url, is_active, created_at, updated_at, telegram_chat_id, language FROM users 
WHERE username = ? COLLATE NOCASE OR email = ? COLLATE NOCASE 
LIMIT 1
`

type GetUserByUsernameOrEmailParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

// Used for smart login: accepts either username or full email
func (q *Queries) GetUserByUsernameOrEmail(ctx context.Context, arg GetUserByUsernameOrEmailParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsernameOrEmail, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramChatID,
		&i.Language,
	)
	return i, err
}

const getUserLanguage = `-- name: GetUserLanguage :one

SELECT language FROM users WHERE id = ?
`

// ============================================
// Language Preference
// ============================================
func (q *Queries) GetUserLanguage(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserLanguage, id)
	var language string
	err := row.Scan(&language)
	return language, err
}

const getUserTelegramChatID = `-- name: GetUserTelegramChatID :one

SELECT telegram_chat_id FROM users WHERE id = ?
`

// ============================================
// Telegram Integration
// ============================================
func (q *Queries) GetUserTelegramChatID(ctx context.Context, id int64) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getUserTelegramChatID, id)
	var telegram_chat_id sql.NullString
	err := row.Scan(&telegram_chat_id)
	return telegram_chat_id, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, username, email, password_hash, full_name, avatar_url, is_active, created_at, updated_at, telegram_chat_id, language FROM users ORDER BY username
`

func (q *Queries) ListAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.AvatarUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TelegramChatID,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password_hash, full_name, avatar_url, is_active, created_at, updated_at, telegram_chat_id, language FROM users WHERE is_active = 1 ORDER BY username
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.AvatarUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TelegramChatID,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserLanguage = `-- name: SetUserLanguage :exec
UPDATE users 
SET language = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type SetUserLanguageParams struct {
	Language string `json:"language"`
	ID       int64  `json:"id"`
}

func (q *Queries) SetUserLanguage(ctx context.Context, arg SetUserLanguageParams) error {
	_, err := q.db.ExecContext(ctx, setUserLanguage, arg.Language, arg.ID)
	return err
}

const setUserTelegramChatID = `-- name: SetUserTelegramChatID :exec
UPDATE users 
SET telegram_chat_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type SetUserTelegramChatIDParams struct {
	TelegramChatID sql.NullString `json:"telegramChatId"`
	ID             int64          `json:"id"`
}

func (q *Queries) SetUserTelegramChatID(ctx context.Context, arg SetUserTelegramChatIDParams) error {
	_, err := q.db.ExecContext(ctx, setUserTelegramChatID, arg.TelegramChatID, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users 
SET full_name = ?, avatar_url = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, username, email, password_hash, full_name, avatar_url, is_active, created_at, updated_at, telegram_chat_id, language
`

type UpdateUserParams struct {
	FullName  string         `json:"fullName"`
	AvatarUrl sql.NullString `json:"avatarUrl"`
	ID        int64          `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.FullName, arg.AvatarUrl, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramChatID,
		&i.Language,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users 
SET password_hash = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"passwordHash"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}
