// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :exec
INSERT OR IGNORE INTO workspace_members (user_id, project_id)
VALUES (?, ?)
`

type AddWorkspaceMemberParams struct {
	UserID    int64 `json:"userId"`
	ProjectID int64 `json:"projectId"`
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error {
	_, err := q.db.ExecContext(ctx, addWorkspaceMember, arg.UserID, arg.ProjectID)
	return err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO projects (key, name, description, lead_id)
VALUES (?, ?, ?, ?)
RETURNING id, key, name, description, lead_id, is_archived, created_at, updated_at
`

type CreateWorkspaceParams struct {
	Key         string         `json:"key"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	LeadID      sql.NullInt64  `json:"leadId"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.LeadID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.LeadID,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocProjectID = `-- name: GetDocProjectID :one
SELECT project_id FROM docs WHERE id = ? LIMIT 1
`

func (q *Queries) GetDocProjectID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDocProjectID, id)
	var project_id int64
	err := row.Scan(&project_id)
	return project_id, err
}

const getIssueProjectID = `-- name: GetIssueProjectID :one
SELECT project_id FROM issues WHERE id = ? LIMIT 1
`

func (q *Queries) GetIssueProjectID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getIssueProjectID, id)
	var project_id int64
	err := row.Scan(&project_id)
	return project_id, err
}

const getReleaseProjectID = `-- name: GetReleaseProjectID :one
SELECT project_id FROM releases WHERE id = ? LIMIT 1
`

func (q *Queries) GetReleaseProjectID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getReleaseProjectID, id)
	var project_id int64
	err := row.Scan(&project_id)
	return project_id, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one

SELECT id, key, name, description, lead_id, is_archived, created_at, updated_at
FROM projects
WHERE id = ? LIMIT 1
`

// ============================================
// Workspace Queries (projects table)
// ============================================
func (q *Queries) GetWorkspaceByID(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.LeadID,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByKey = `-- name: GetWorkspaceByKey :one
SELECT id, key, name, description, lead_id, is_archived, created_at, updated_at
FROM projects
WHERE key = ? COLLATE NOCASE LIMIT 1
`

func (q *Queries) GetWorkspaceByKey(ctx context.Context, key string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByKey, key)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.LeadID,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isUserAdmin = `-- name: IsUserAdmin :one
SELECT is_admin FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) IsUserAdmin(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, isUserAdmin, id)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const listAllWorkspaces = `-- name: ListAllWorkspaces :many
SELECT id, key, name, description, lead_id, is_archived, created_at, updated_at
FROM projects
WHERE is_archived = 0
ORDER BY name
`

func (q *Queries) ListAllWorkspaces(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listAllWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.LeadID,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT u.id, u.username, u.email, u.full_name, u.avatar_url, u.language, u.is_admin, u.created_at, u.updated_at
FROM workspace_members wm
JOIN users u ON wm.user_id = u.id
WHERE wm.project_id = ?
ORDER BY u.username
`

type ListWorkspaceMembersRow struct {
	ID        int64          `json:"id"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	FullName  string         `json:"fullName"`
	AvatarUrl sql.NullString `json:"avatarUrl"`
	Language  string         `json:"language"`
	IsAdmin   bool           `json:"isAdmin"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, projectID int64) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMembersRow{}
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.FullName,
			&i.AvatarUrl,
			&i.Language,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
SELECT p.id, p.key, p.name, p.description, p.lead_id, p.is_archived, p.created_at, p.updated_at
FROM projects p
WHERE p.is_archived = 0
  AND (
    EXISTS (SELECT 1 FROM users u WHERE u.id = ? AND u.is_admin = 1)
    OR EXISTS (SELECT 1 FROM workspace_members wm WHERE wm.project_id = p.id AND wm.user_id = ?)
  )
ORDER BY p.name
`

type ListWorkspacesForUserParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"userId"`
}

func (q *Queries) ListWorkspacesForUser(ctx context.Context, arg ListWorkspacesForUserParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspacesForUser, arg.ID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.LeadID,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllWorkspaceMembers = `-- name: RemoveAllWorkspaceMembers :exec
DELETE FROM workspace_members WHERE project_id = ?
`

func (q *Queries) RemoveAllWorkspaceMembers(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, removeAllWorkspaceMembers, projectID)
	return err
}

const removeWorkspaceMember = `-- name: RemoveWorkspaceMember :exec
DELETE FROM workspace_members
WHERE project_id = ? AND user_id = ?
`

type RemoveWorkspaceMemberParams struct {
	ProjectID int64 `json:"projectId"`
	UserID    int64 `json:"userId"`
}

func (q *Queries) RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeWorkspaceMember, arg.ProjectID, arg.UserID)
	return err
}

const userHasWorkspaceAccess = `-- name: UserHasWorkspaceAccess :one
SELECT EXISTS (
    SELECT 1 FROM users u
    WHERE u.id = ? AND u.is_admin = 1
) OR EXISTS (
    SELECT 1 FROM workspace_members wm
    WHERE wm.user_id = ? AND wm.project_id = ?
) AS has_access
`

type UserHasWorkspaceAccessParams struct {
	ID        int64 `json:"id"`
	UserID    int64 `json:"userId"`
	ProjectID int64 `json:"projectId"`
}

func (q *Queries) UserHasWorkspaceAccess(ctx context.Context, arg UserHasWorkspaceAccessParams) (sql.NullBool, error) {
	row := q.db.QueryRowContext(ctx, userHasWorkspaceAccess, arg.ID, arg.UserID, arg.ProjectID)
	var has_access sql.NullBool
	err := row.Scan(&has_access)
	return has_access, err
}
